### ISSUE TITLE
Dia II doesn't overwrite Bio

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4284] opened 2017-11-25 20:35 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** 2fe3c089

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
New pull/ new build... left settings.lua as default (they should only be affecting "same tier" anyway)
casted bio on a mob... then immediately casted dia II and got the response:
![dia](https://user-images.githubusercontent.com/30469395/33234524-d3335ba4-d1ed-11e7-8c8c-69ddede091ef.jpg)

**Comment by TeoTwawki** [comment] 2017-11-26 18:19
duplicate of #2088

which actually lists more problems with dio/bio that just this

**Closed by TeoTwawki** 2017-11-26 18:19 UTC
