### ISSUE TITLE
Client crash on zoning

### ISSUE THREAD

**Issue by ymkc** [DarkstarProject/darkstar#3384] opened 2016-09-23 14:38 UTC
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_1

**_Server Version_** (type `@revision` in game) **:**
424e429

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Leaving a Dynamis zone sometimes crashes the client while just producing a warning on the server:
[Warning] zlib_compress: ran out of space (9812 : 5 : 9816 : 1)
[Warning] zlib_compress: ran out of space (7729 : 11 : 7736 : 4294967198)
[Warning] zlib_compress: ran out of space (9814 : 6 : 9816 : 2)

doesn't seem to be happening all the time, but e.g. leaving dynamis-jeuno by `@zone` to any other zone seems to trigger it quite often

probably related to 47b3a5f9a3845dca94f5d8a3a9dec340e148c411

game server is a 32bit binary running on amd64 linux kernel

**Comment by Cloudef** [comment] 2017-03-02 13:55
Dupe of https://github.com/DarkstarProject/darkstar/issues/3394 I'll post more information how you can help me to fix this.

**Comment by takhlaq** [comment] 2017-03-02 14:01
closing in favour of #3394 cause it has more info

**Closed by takhlaq** 2017-03-02 14:01 UTC
