### ISSUE TITLE
crash server dynamis bastol, windurst and jeuno.

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1554] opened 2015-06-08 22:56 UTC
When I made the dynamis of Windurst and Jeuno, at final boss, the server crash.

[18:20:51][Debug] duration: 9000*** Error in `./dsgame': malloc(): memory corruption: 0x000000001b44fde0 ***
Abandon (core dumped)

**Comment by m241dan** [comment] 2015-06-09 13:40
Its the "spawn second half" lua binding that causes this. As to why, I don't know, I just commented it out on my server.

**Comment by AlexandreCA** [comment] 2015-06-10 18:42
I don't have try for the other dynamis. I dare not of scared of crash the server again

**Comment by xdemolish** [comment] 2015-07-02 22:04
duplicate of https://github.com/DarkstarProject/darkstar/issues/1370

**Closed by xdemolish** 2015-07-02 22:04 UTC
