### ISSUE TITLE
Martial Arts not taken into account for re-engage delay

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2654] opened 2016-01-21 18:11 UTC
Not sure if this was fixed with the ai rewrite, but since there was no issue about it, it probably wasn't. It should be taken into account when the player has a h2h weapon equipped.

**Comment by teschnei** [comment] 2016-01-22 00:32
Just gonna close this since it's not even confirmed

**Closed by teschnei** 2016-01-22 00:32 UTC

**Comment by Biogreg82** [comment] 2016-01-22 00:35
I have felt this, but I can not confirm on the code, but I have noticed the
draw time "feels slow"

**Comment by teschnei** [comment] 2016-01-22 00:47
I checked the code just now, it's taking into account all delay reductions
(it uses the same function as the auto attack timer)

**Comment by Hozu** [comment] 2016-01-22 07:45
Well I'll be more than happy to pass along the fact that this is a not a real issue to players.

**Comment by teschnei** [comment] 2016-01-22 07:49
I of course have no idea about its behaviour on the stable branch :)
