### ISSUE TITLE
alliance treasure pool crashing server

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#834] opened 2015-01-23 03:09 UTC
dump uploading right now will post ASAP

**Comment by Scavenge** [comment] 2015-01-23 03:10
didn't mean to open that yet, hit enter on the wrong line

**Comment by teschnei** [comment] 2015-01-23 03:10
Duplicate of #764

**Comment by Scavenge** [comment] 2015-01-23 03:10
if you're sure, but this was not happening at all until last night's update to alliances

**Comment by teschnei** [comment] 2015-01-23 03:11
i am fairly confident in that claim, but I will look anyways if you upload it

**Comment by Scavenge** [comment] 2015-01-23 03:42
ok I spoke incorrectly it looks like something to do with alliance treasurepool, have had a few misleading crashes in different places like vector but every callstack points back to treasurepool at some point.

dump:
https://www.dropbox.com/s/puwc49ha47i5luw/alliance%20crash%201-22.7z?dl=0

**Comment by teschnei** [comment] 2015-01-23 03:57
yeah, it's the same crash :)

**Comment by Scavenge** [comment] 2015-01-23 04:12
ok sorry then. just seemed odd because we're getting this crash very often now and the last week or so has been totally fine for alliances.  perhaps it's just a difference in player activity; thanks.

**Comment by Scavenge** [comment] 2015-01-23 05:17
to give you some more info if it helps, the alliance will cause multiple crashes in a row because when people log back in, offline players are still in their party.  attempting to remove one by one doesn't work, and when they use /pcmd leave and then create a new party, the first time they invite a player, it instantly pulls offline players back into the party.  if an alliance is attempted when these things happen, it crashes.

**Comment by teschnei** [comment] 2015-01-23 05:19
parties/alliances are pulled from account_sessions and account_parties.  they should be cleared when the server starts, depending on whether you have a single server or multiple

**Comment by Scavenge** [comment] 2015-01-23 05:21
we have a single server, I wager I should manually clear them until I figure out why they aren't getting cleared

**Comment by Scavenge** [comment] 2015-02-15 18:43
map.cpp is only clearing accounts_sessions on startup, going to try adding a line to clear parties as well

**Comment by xdemolish** [comment] 2015-03-02 16:46
still an issue?

**Comment by xdemolish** [comment] 2015-04-06 14:39
i'll take the lack of response as a no!

**Closed by xdemolish** 2015-04-06 14:39 UTC
