### ISSUE TITLE
Synthesis possible without crystal

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#2051] opened 2015-09-08 08:21 UTC
If you navigate to the synthesis history and spam enter fast enough, the OK button will not grey out fast enough to prevent you synthesizing even if you do not have the needed crystal in inventory.

**Comment by whasf** [comment] 2015-09-13 21:12
Weird because the server is checking to see that you have a valid  synth

**Comment by metalfiiish** [comment] 2017-11-29 00:18
Unable to reproduce anymore. Seems to have been fixed since this was opened. Can someone close this?

**Closed** 2017-11-29 01:40 UTC
