### ISSUE TITLE
Elevator at Pso'Xia

### ISSUE THREAD

**Issue by lichtl** [DarkstarProject/darkstar#1340] opened 2015-04-22 06:34 UTC
Hi,

there seems to be a problem to enter/leave some of the elevators in Pso'Xia

Example: 16814505 TOWER_E_Lift_1 @pos -20 16  20
You are able to enter the elevator which travel downstairs but there you're stuck and either unable to leave or to enter the elevator.

I've already tried to work with the X/Y/Z coordinates of 16814505  and the lower endpoint but without any noticable success. I'll try to come into irc later today and maybe someone can gave me a hint on how to fix those ones myself.

**Comment by Turttle** [comment] 2015-04-23 01:06
is it only on the 16814505?

**Comment by lichtl** [comment] 2015-04-23 06:55
Hi,

just checked all elevators

16814464 - @092 - unable to enter/exit elevator (either at upper or lower pos)
16814442 - @090 - OK
16814477 - @09a - not sure about this one since the doors are closed. (so unable to enter/exit rooms)
16814461 - @091 -  unable to enter/exit elevator (at either position)

**Comment by nesstea** [comment] 2015-04-29 17:35
Dumb elevators ^^

**Comment by xdemolish** [comment] 2015-07-02 22:09
duplicate of https://github.com/DarkstarProject/darkstar/issues/752

**Closed by xdemolish** 2015-07-02 22:09 UTC
