### ISSUE TITLE
Scholar's Embrava doesn't grant mp or haste

### ISSUE THREAD

**Issue by Caeva** [DarkstarProject/darkstar#5718] opened 2019-02-07 07:14 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
30181222_1

**_Source Branch_** (master/stable) **:** 
Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
I play SCH on Supernova and when I reported this bug I was directed here to report it; there isn't any custom code as far as I know.
if there's anything any information you need i'll try my best to help, however i'm pretty illiterate in terms of programming/coding

**Comment by Delkathus** [comment] 2019-02-07 08:21
https://github.com/DarkstarProject/darkstar/pull/5716

**Comment by TeoTwawki** [comment] 2019-02-09 17:39
Was this caused by, or fixed by, that?

**Comment by Delkathus** [comment] 2019-02-09 21:52
It was fixed before the issue was opened.

**Closed** 2019-02-10 01:02 UTC
