### ISSUE TITLE
Guild NPCs don't reset requested item; request the same item multiple times, and refuse to accept trades.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1713] opened 2015-07-13 15:13 UTC
This happens over all guild NPCs, so it's hard to define the issue exactly, but for example:

Goldsmith NPC: Ellard

Yesterday Requested: Spark Bilbo, turned in fine.
Today Requested: Spark Bilbo, won't accept trade in.

"JP midnight" has ticked over; it's been over 36 hours since Spark Bilbo was first requested.

I will try to narrow down the details further.

**Comment by xipies** [comment] 2015-07-14 21:46
Empirically, this seems to be happening on Classic for over a week now. Classic normally resets after midnight for america/new_york time zone. I am not sure if that is the default, though.

**Comment by xipies** [comment] 2015-07-14 22:05
Duplicate of #1519?

**Comment by dazusu** [comment] 2015-07-14 22:15
Oh yes, so it is.. didn't realise I had already reported it.

**Closed** 2016-05-08 23:44 UTC
