### ISSUE TITLE
Doom removal chance is incorrect

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#3852] opened 2017-04-18 20:04 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
current

**_Server Version_** (type `@revision` in game) **:**
current

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

https://www.bg-wiki.com/bg/Cursna

- [ ] Removal rate is affected by healing skill - 10% at 0, 30% at 600, and 43% at 1000. No known cap.

This post adds another data point - 26% at 500. https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6880062&viewfull=1#post6880062

- [x] Holy water is 33% - DSP has it at 25%. https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)/page38 (note: that post erroneously says Cursna removes at 30% chance at 500 skill).

- [x] Hallowed Water is the same rate as Holy water (33%) - DSP has it at 50%. https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6519212&viewfull=1#post6519212

- [x] Modifers that affect the Doom removal rate of Cursna increases it by a percent of the current removal rate. For example, +10 modifier at 0 skill would change the rate from 10% to 11%, while at 600 skill it would be from 30% to 33%. Note that there is a cap to removal, at 99%. https://www.bluegartr.com/threads/112776-Dev-Tracker-Findings-Posts-(NO-DISCUSSION)?p=6635343&viewfull=1#post6635343

Again, I can't test so I can't be making pull requests here.

**Comment by R3P0FFXI** [comment] 2017-04-18 20:59
@Hozu This may be a duplicate of a previous issue, Doom actually has not been working on DSP for a while due to a tick issue

https://github.com/DarkstarProject/darkstar/issues/3599

**Comment by Hozu** [comment] 2017-04-18 21:00
Nah that's a separate issue. The scripts involving removal of Doom have been wrong since the beginning.

**Comment by TeoTwawki** [comment] 2017-04-18 22:12
@R3P0FFXI he just posted the actual numbers of the status in trunk vs what the devs have actually stated they are in retail. Nothing to do with the fact doom is wearing off before killing you *when not removed*.

**Comment by TeoTwawki** [comment] 2017-04-18 22:43
https://github.com/DarkstarProject/darkstar/commit/f8bbb6d7ce5e1cb38b93f67ffe6b22db0fb6c3e5 
I took care of the 2 items, that just leaves the spell left

**Closed** 2019-05-07 09:04 UTC
