### ISSUE TITLE
mob accuracy or player evasion very off

### ISSUE THREAD

**Issue by Scavenge** [DarkstarProject/darkstar#831] opened 2015-01-22 07:56 UTC
repots that evasion is bugged have been consistently coming in from players, testing it myself as a 75 fully gear ninja with +70 evasion and +20 agi didn't dodge a single attack from an easy prey colibri in wajaom.  similar experiments have shown similar results.  their accuracy is not 100%, more like a consistent 95% according to a few parses i've done, hovering between 93-97% even against too weak mobs.

**Comment by Scavenge** [comment] 2015-01-22 09:58
in a strange twist, my GM character seems to not have this issue even with godmode turned off and his level set to 75 as well on ninja. the only different seems to be that he was not wearing a full evasion set... that might not be related but still very very odd.  on my normal character i'm lucky to get a single dodge even when i just stand there and let the battle drag on.  meanwhile on my gm char he dodges about 75% of the attacks

**Comment by teschnei** [comment] 2015-01-22 21:51
Duplicate of #750

**Closed by teschnei** 2015-01-22 21:51 UTC

**Comment by Scavenge** [comment] 2015-01-22 22:08
ya didn't see that til after sorry
