### ISSUE TITLE
Sandy Mission 2-3, Halver Doesn't Do Anything

### ISSUE THREAD

**Issue by LordKaT** [DarkstarProject/darkstar#1032] opened 2015-03-06 01:51 UTC
Halver is somewhat retarded. I had to clean up his onTrigger code to figure out what the heck was going on and why we couldn't finish Sandy Mission 2-3 and get our Adventurer's Certificate.

So, the code itself only checks if currentMission == JOURNEY_ABROAD
But the mission itself is advanced to JOURNEY_TO_WINDURST2
Somewhere along the way there was a check for MissionStatus == 11.
I don't know where this comes from. MissionStatus is set to 10 on completion.

I also cleaned up the code a bit. There were a few sections where Halver could fall through to multiple cutscenes if you were doing a couple of things at once. This makes it so that you're forced to talk to him multiple times.

    --onTrigger
    function onTrigger(player,npc)
    local pNation = player:getNation();
    local currentMission = player:getCurrentMission(pNation);
    local WildcatSandy = player:getVar("WildcatSandy");
    local MissionStatus = player:getVar("MissionStatus");

	-- Lure of the wildcat
	if (player:getQuestStatus(SANDORIA, LURE_OF_THE_WILDCAT_SAN_D_ORIA) == QUEST_ACCEPTED and player:getMaskBit(WildcatSandy, 16) == false) then
		player:startEvent(0x022e);
		return;
	end

	-- "Flagsando"??????
	if (player:getVar("Flagsando") == 1) then
		if (player:getFreeSlotsCount() == 0) then
			player:messageSpecial(ITEM_CANNOT_BE_OBTAINED, 181);
		else
			player:setVar("Flagsando",0);
			player:addItem(181);
			player:messageSpecial(ITEM_OBTAINED, 181);
		end
		return;
	end

	-- Blackmail quest
	if (player:getQuestStatus(SANDORIA, BLACKMAIL) == QUEST_ACCEPTED and player:hasKeyItem(SUSPICIOUS_ENVELOPE)) then
		player:startEvent(0x0225);
		player:setVar("BlackMailQuest", 1);
		player:delKeyItem(SUSPICIOUS_ENVELOPE);
		return;
	end

	-- Heir to the Light
	if (player:hasCompletedMission(SANDORIA,THE_HEIR_TO_THE_LIGHT)) then
		player:startEvent(0x001f);
		return;
	end

	if (player:getCurrentMission(SANDORIA) == THE_HEIR_TO_THE_LIGHT and player:getVar("SANDO92") >= 2 and player:getVar("SANDO92") <=5) then
		player:startEvent(0x001d);
		return;
	end

	if (player:getCurrentMission(SANDORIA) == THE_HEIR_TO_THE_LIGHT and player:getVar("SANDO92") == 6) then
		player:startEvent(0x001e);
		return;
	end

	if (player:getCurrentMission(SANDORIA) == THE_HEIR_TO_THE_LIGHT and player:getVar("SANDO92") == 7) then
		player:startEvent(0x0009);
		return;
	end

	-- Nation Missions
	if (pNation == SANDORIA) then
		if (currentMission == JOURNEY_ABROAD) then
			if (MissionStatus == 0) then
				player:startEvent(0x01f9);
			elseif (MissionStatus == 11) then
				player:startEvent(0x01fb);
			else
				player:startEvent(0x0214);
			end
			return;
		end

		-- JOURNEY_ABROAD's final scene
		if (currentMission == JOURNEY_TO_WINDURST2) then
			if (MissionStatus == 10) then
				player:startEvent(0x01fb);
			end
			return;
		end

		if (currentMission == APPOINTMENT_TO_JEUNO) then
			if (MissionStatus == 0) then
				player:startEvent(0x01fc);
			end
			return;
		end

		if (currentMission == THE_RUINS_OF_FEI_YIN) then
			if (MissionStatus == 9) then
				player:startEvent(0x0215);
			end
			if (MissionStatus == 10) then
				player:showText(npc, HALVER_OFFSET+334);
			end
			if (MissionStatus == 12) then
				if (player:hasKeyItem(BURNT_SEAL)) then
					player:startEvent(0x0216);
				end
			end
			return;
		end

		if (currentMission == THE_SHADOW_LORD) then
			if (MissionStatus == 0) then
				player:startEvent(0x0222);
			end
			if (MissionStatus == 4) then
				if (player:hasKeyItem(SHADOW_FRAGMENT)) then
					player:startEvent(0x0224);
				end
			end
			if (MissionStatus == 5) then
				player:showText(npc,HALVER_OFFSET+471);	
			end
			return;
		end

		-- Mission 255???
		if (currentMission == 255) then
			if (player:hasCompletedMission(SANDORIA, THE_SHADOW_LORD)) then
				player:showText(npc, HALVER_OFFSET+500);
			end
			return;
		end

		if (currentMission == LEAUTE_S_LAST_WISHES) then
			if (MissionStatus == 0) then
				player:startEvent(0x0019);
			end
			if (MissionStatus == 1) then
				player:startEvent(0x0017);
			end
			if (MissionStatus == 2) then
				player:startEvent(0x0018);
			end
			if (MissionStatus == 3) then
				player:startEvent(0x0016);
			end
			return;
		end		

		-- Mission 8-1
		if (currentMission == COMING_OF_AGE) then
			if (MissionStatus == 1) then
				player:startEvent(0x003A);
			end
			if (MissionStatus == 3) then
				if (player:hasKeyItem(DROPS_OF_AMNIO)) then
					player:startEvent(0x0066);
				end
			end
			return;
		end
		return;
	end

	if (pNation == BASTOK) then
		if (currentMission == THE_EMISSARY) then
			if (MissionStatus == 3) then
				player:startEvent(0x01f5);
			end
		end

		if (currentMission == THE_EMISSARY_SANDORIA) then
			player:showText(npc, HALVER_OFFSET+279);
		end

		if (currentMission == THE_EMISSARY_SANDORIA2) then
			MissionStatus = MissionStatus;
			if (MissionStatus == 8) then
				player:startEvent(0x01f7);
			elseif (MissionStatus <= 10) then
				player:showText(npc, HALVER_OFFSET+279);
			end
		else
			player:showText(npc, HALVER_OFFSET+1092);
		end
		return;
	end

	if (pNation == WINDURST) then
		if (currentMission == THE_THREE_KINGDOMS) then
			if (MissionStatus < 3) then
				player:startEvent(0x0214);
			end
			return;
		end
		if (currentMission == THE_THREE_KINGDOMS_SANDORIA or currentMission == THE_THREE_KINGDOMS_SANDORIA2) then
			if (MissionStatus == 3) then
				player:startEvent(0x01F6);
			elseif (MissionStatus == 8) then
				player:startEvent(0x01F8);
			else
				player:showText(npc, HALVER_OFFSET+279);
			end
		end
		return;
	end
	player:showText(npc, HALVER_OFFSET+1092);
    end;

**Comment by gedads** [comment] 2015-03-09 08:16
hi, i tried too to clean halver but didn't finished it (i mean all 3 paths) using more specific vars like WINDURST23, BASTOK23 SANDO 23 for each starter mission then WINDURST23SB OR BS for choosen path etc 
 "So, the code itself only checks if currentMission == JOURNEY_ABROAD
But the mission itself is advanced to JOURNEY_TO_WINDURST2"
in retail you start journey abroad, you have to visit an ambassy, once your path is chosen, you finish mission journey abroad to start journey to windurst 1 or journey to bastok 1then once it's done you complete that mission to start journey to bastok2 or to windurst 2. In your log on retail you'll not see 1 or 2 just

completed mission journey abroad
                               journey to bastok
                              journey to windurst 
if you choosed the way bastok-> windurst for sando mission 2-3

**Comment by LordKaT** [comment] 2015-03-09 14:42
I can look into the other paths and clean them up if you want.

**Comment by gedads** [comment] 2015-03-09 20:28
sure if you add the missing cs (mostly extra dialogs that reflect your progression)

**Comment by xdemolish** [comment] 2015-04-07 09:42
it's going to check every single one of those conditions each time you run the script
also, duplicate of https://github.com/DarkstarProject/darkstar/issues/933 and https://github.com/DarkstarProject/darkstar/issues/285

**Closed by xdemolish** 2015-04-07 09:42 UTC
