### ISSUE TITLE
BST even more broken from recent commit

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4212] opened 2017-11-08 05:56 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

BST pets that are charmed have had an issue where they won't aggro when losing charm while engaged:
https://github.com/DarkstarProject/darkstar/issues/4087
But, since this commit:
https://github.com/DarkstarProject/darkstar/commit/94870df75ea22c35355a9ff95780eda24e4f9f76
Now BST pets that are charmed won't aggro period when losing charm.
Tested by reverting that commit and charmed pets are back to aggroing after losing charm (as long as they are Not engaged), Though, that leaves the issue of uncharmed mobs not being removed from hate list: https://github.com/DarkstarProject/darkstar/issues/4140 unresolved... as well as the issue where charmed pets will not aggro if engaged unresolved.

**Comment by teschnei** [comment] 2017-11-08 06:06
duplicate of #4087

**Closed by teschnei** 2017-11-08 06:06 UTC

**Comment by Wiggo32** [comment] 2017-11-08 06:14
This isn't a duplicate... this commit adds additional issues to https://github.com/DarkstarProject/darkstar/issues/4087

**Comment by teschnei** [comment] 2017-11-08 06:18
it is the same issue, it's a duplicate
