### ISSUE TITLE
King Arthro

### ISSUE THREAD

**Issue by Skanless** [DarkstarProject/darkstar#3998] opened 2017-08-20 09:31 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **30170728_2:**

**_Server Version_** (type `@revision` in game) **b079fa65cf51187adf05878a8515582c9f5d6071:**

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **Cant reproduce until 21-24hr but was told to put in a ticket, me and my brother have been killing KA last 4 nights everything fine, then tonight after we killed all 10 KC he didn't pop.**

**Comment by Jessland86** [comment] 2017-08-20 16:01
@Skanless This should be on our issue tracker.

**Comment by TeoTwawki** [comment] 2017-08-20 19:25
This happened before on legion and then magically went away on its own. Maybe it should be on this tracker.

When this happened before, the variable simply stopped incrementing with no cause.

There was no custom code involved and I could find no reason for this when R3P0FFXI asked me to look into it, and I recall another server speaking of it on IRC but I was unable to reproduce the issue..

**Comment by Hokuten85** [comment] 2017-08-21 19:45
Do we know if @Skanless began killing the Knight Crabs before all of them popped?  I ran into this on my own personal server, and King Arthro didn't pop because onMobSpawn for Knight Crabs resets the counter...unless I'm reading that wrong.  I moved SetServerVariable("[POP]King_Arthro",0); to King Arthro's death handler.

**Comment by TeoTwawki** [comment] 2017-08-21 20:31
I just removed that possibility in e9dffc33d0822c4a1cdaecdc7265fe305955bca8 the count would also have been off before he got there if someone else had done that and not reported the bug



aaand just realized the crabs do it on their death if the var was already enough to pop arthro. Redundant much? Oi.

**Comment by Jessland86** [comment] 2017-08-22 03:19
He said they were all popped before he started killing.

**Comment by metalfiiish** [comment] 2017-11-28 15:34
These issues should be resolved in the merged code from #4292 . Could probably close this ticket.

**Closed** 2017-11-28 18:25 UTC
