### ISSUE TITLE
Issues with Draw In

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4122] opened 2017-10-10 16:14 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170905_5

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Draw in can land the entire party inside a wall and unable to move. I've experienced this with the NM's most frequently in Xarcabard (Boreals) due to the tight space with which you have to fight in. But, it has also happened in La Thiene fighting the Ram NM when I was pulled into a hill and stuck under the terrain.

**Comment by TeoTwawki** [comment] 2017-10-10 16:36
#2511

**Comment by takhlaq** [comment] 2017-11-19 10:43
duplicate of https://github.com/DarkstarProject/darkstar/issues/2511
not planning on fixing this til we get round to using collision meshes

@bendangelo if you get a chance, could you hop into discord send me or devi maplib src? would probably help with finding shared collision mesh groupings (assuming xi uses them like xiv does)

**Closed by takhlaq** 2017-11-19 10:43 UTC
