### ISSUE TITLE
When the treasure pool is full, new items are immediately distributed.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2877] opened 2016-03-07 19:04 UTC
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
1da5803

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Reproduce: When the treasure pool is full, and new items drop, they are immediately distributed or lost. Kill monsters. Lots. While in a party.

Expected: When the treasure pool is full, new items should enter the pool and push out the items which have been in the pool longest for distribution. This forced-push should not happen to 'rare' items in the pool, unless the pool is completely full of rare items with no standard items that can be pushed out.

**Comment by bendangelo** [comment] 2016-03-07 19:47
This will be easy to fix with the test suite. Let me see if I can write a test for it.

**Comment by teschnei** [comment] 2016-03-07 19:52
This is already implemented, but I probably messed up a check when converting from time_t to chrono types.

**Comment by Hozu** [comment] 2016-05-06 02:25
Well I flipped the check here https://github.com/DarkstarProject/darkstar/blob/master/src/map/treasure_pool.cpp#L178 and the other two and there wasn't any noticeable change. It still behaved incorrectly. I don't have any idea what the problem is.

**Comment by wrenffxi** [comment] 2016-10-15 15:00
Fixed in PR #3460

**Closed** 2017-02-04 05:17 UTC
