### ISSUE TITLE
Merits into Enmity Minus giving Handbell Skill

### ISSUE THREAD

**Issue by IxAalexI** [DarkstarProject/darkstar#1905] opened 2015-08-09 23:25 UTC
Title! This is on a fresh pull btw.

**Comment by teschnei** [comment] 2015-08-09 23:28
Merits that were previously into enmity minus or new merits?

**Comment by IxAalexI** [comment] 2015-08-09 23:31
New merits, after rebuild of fresh pull.

**Comment by IxAalexI** [comment] 2015-08-09 23:39
I checked the DB for proper values @ char_merits and merits tables, and it is calling the right values as far as the DB is concerned so I'm guessing a source issue?

**Comment by Hozu** [comment] 2015-08-10 22:49
I believe this has been an issue for a while now.. Anything you merit in the Other category adds various things in the Magic Skills in the UI. Enmity+ gives Geomancy, while Enmity- gives Handbell. The rest give ' skill.

What is new, however, is a player informed me that when they merited Ninjutsu skill, they also got Geomancy skill in addition to the intended result. Again, not sure if it's just a UI thing or if it actually gives such skill. I have not tested this myself.

By give, I'm not entirely sure if it actually give said skill or not.

**Comment by maxtherabbit** [comment] 2015-08-12 15:04
I was able to duplicate the merits for enmity +/- going into geomancy and handbell

the other issues mentioned (ninjutsu and the other 'other' category merits) were fixed by 55cd5d3 I believe

**Comment by Hozu** [comment] 2015-08-12 15:20
Nah this is after that commit. Meriting Ninjitsu still gives that skill, it just also gives Geomancy or w/e. Or were you unable to duplicate that? If not, I'll have to ask that player again.

**Comment by maxtherabbit** [comment] 2015-08-12 15:21
the problem is caused by geomancy and handbell being defined in the merit header but lacking corresponding rows in the merits.sql - I don't immediately see a way to prevent this behavior without totally rewriting the merit system, so I'm going to add rows for geo and handbell and call it good

**Comment by maxtherabbit** [comment] 2015-08-12 15:22
I merited ninjutsu and it only showed up as ninjutsu

**Comment by Hozu** [comment] 2015-08-12 15:29
Ok, well that's one less bug to fix.

**Closed** 2015-08-12 15:35 UTC
