### ISSUE TITLE
COP 8-3 When Angels Fall Elevators Broken

### ISSUE THREAD

**Issue by R3P0FFXI** [DarkstarProject/darkstar#2077] opened 2015-09-15 13:55 UTC
All 5 elevator towers in The Garden of Ru'Hmet on 2F for COP 8-3 are broken players are unable to get to the rooms to get the lights needed to complete the missions.

**Comment by TeoTwawki** [comment] 2015-09-15 14:40
From what I hear they will trigger just once. and the break.

**Comment by Sacshop** [comment] 2015-09-15 14:50
You must log after using every single porter - or use a pseudo zone method in order for each player to continue to climb the tower

**Comment by Hozu** [comment] 2015-09-15 17:33
It's onEventFinish issues again - that function is supposed to be clearing the variable upon completing the elevator event, but it's not.

**Comment by TeoTwawki** [comment] 2015-09-15 17:53
I don't see that the var even means anything. Its being set one in onEventUpdate and set zero in onEventFinish, but I see nowhere checking what the vars state is so I don't think the var is the cause (but looks like its a useless var anyway though..)

onEventFinish does the setPos() bit and might be a prob but my understanding is the event never starts so theres a problem with regions being entered?

**Comment by TeoTwawki** [comment] 2015-09-15 17:56
I stand corrected:
```lua
function onRegionEnter(player,region)	
 if (player:getVar("Ru-Hmet-TP")==0 and player:getAnimation()==0) then	
```

**Comment by TeoTwawki** [comment] 2015-09-15 17:56
Saw it right after posting

**Comment by teschnei** [comment] 2015-09-15 17:56
It's checked in onRegionEnter for RuHmet

**Comment by TeoTwawki** [comment] 2015-09-15 17:56
@teschnei you are 5 seconds to late

**Comment by teschnei** [comment] 2015-09-15 17:59
phone typing speed, e-mail speed, blah blah..

I have no idea what it's intended effect is, though.  Are they not as simple as "walk into region, start cutscene"?

**Comment by Hozu** [comment] 2015-09-15 18:00
Something about a comment saying that the var check exists to not play a CS multiple times in some instance, though I haven't really investigated it.

**Comment by TeoTwawki** [comment] 2015-09-15 18:00
@teschnei I've no idea what the var is for yet, crazy formatting makes me wanna rip my eyes out

**Comment by TeoTwawki** [comment] 2015-09-15 18:02
@teschnei whatever was wrong that this got used for, I am 99% sure a variable in the database was the wrong answer anyway.

**Comment by teschnei** [comment] 2015-09-15 18:03
Maybe if it puts you into another region (downward cutscene)? Don't
remember if ruhmet teleports put you into the one for going down. Either
way, onEventFinish isn't firing or the logic is wrong. Pretty easy to debug
I think

**Comment by Hozu** [comment] 2015-09-15 18:28
I'm 99% certain the separate areas in the Garden are laid out horizontally rather than stacked vertically. I never looked at the Palace though.

The elevators used to work before the general onEventFinish issue that broke a ton of things.

**Comment by teschnei** [comment] 2015-09-15 18:38
Sorry, what I meant was that maybe the reason for the var was so that the onRegionEnter didn't process another event immediately after finishing the current one.  IIRC, the teleports are two-way, thus you would activate the event (to go back where you just came from) as soon as you arrived at your destination.  I meant up as in forwards, as they are usually described as "towers" (the map kind of reflects that, though the actual x/z positions are not vertical, as you say)

**Comment by TeoTwawki** [comment] 2015-09-15 18:44
I just tested and that is exactly what the var does. You remove var and you get an event called while an event is running.

**Comment by TeoTwawki** [comment] 2015-09-15 18:46
And var is not the cause of the next event not started -its the fact onEventFinish never runs, just like the other recent issues elsewhere (My prints for onEventFinish never happened).

**Comment by teschnei** [comment] 2015-09-16 00:25
ddefe58e8445672366d343f672b837149b8f9e53

**Closed by teschnei** 2015-09-16 00:25 UTC
