### ISSUE TITLE
Tame has some minor issues

### ISSUE THREAD

**Issue by Wiggo32** [DarkstarProject/darkstar#4268] opened 2017-11-22 18:25 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171103_1

**_Server Version_** (type `!revision` in game) **:** unknown

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Some things I noticed with the new implementation of Tame:
1. Characters should be able to use Tame on mobs that were aggro'd by other players as long as no action has been performed against said mob. Referenced: http://ffxiclopedia.wikia.com/wiki/Tame I also confirmed it myself on retail.
2. As a 99 BST, I missed tame on a Rock Lizard and the message was:
![tame_miss](https://user-images.githubusercontent.com/30469395/33143348-3b08baba-cf7f-11e7-9948-0d2db4d56b9b.jpg)
This is when tame is 'able' to succeed but just fails the rolls.
3. When tame is Not able to succeed (case of beastmen, mobs acted on with anything other than charm, etc.) the message is:
![tame_fail](https://user-images.githubusercontent.com/30469395/33143496-a7fb94ee-cf7f-11e7-85d7-9a7caca3d23b.jpg)
4. When tame is successful, the message is:
![tame_success](https://user-images.githubusercontent.com/30469395/33143535-caa8df24-cf7f-11e7-9f52-24d79314af00.jpg)
And a successfully tamed mob will become immediately still for a few moments before moving again.

**Comment by teschnei** [comment] 2017-11-22 18:31
When you write these, can you include both what is observed and what is
expected (from DSPs point of view, I am guessing these are what is
"expected").  1 and 2 should be working, assuming I am understanding the
issue correctly.  Not sure if you're saying there is functionality missing
or just messages are wrong.

**Comment by Hozu** [comment] 2017-11-22 19:41
Since you have retail it might not be a bad idea to test to see if INT really does affect Tame. Doesn't sound right at all to me, tbh, even if the wiki says so.

**Comment by TeoTwawki** [comment] 2017-11-22 20:09
> Since you have retail it might not be a bad idea to test to see if INT really does affect Tame. Doesn't sound right at all to me, tbh, even if the wiki says so.

The [bg page on it](https://www.bg-wiki.com/bg/Tame) doesn't mention INT at all, so might have been conjecture somebody never confirmed that then became defacto information via wiki. We'll need to find another source that shows they did some testing or just get on retail to confirm if it is INT modified or not.

also [lolGahoo](http://ffxiclopedia.wikia.com/wiki/Tame?diff=prev&oldid=172850)

**Comment by Wiggo32** [comment] 2017-11-22 20:25
kj: Sure no problem, I will try to provide more info like you suggested. As far as No. 1 - In retail, I was successfully able to tame a mob that was aggro'd by and attacking another player completely outside my party. In dsp, I cannot tame a mob aggro'd by anyone other than myself. For the others, those are all the messages I've gotten from retail. And finally, every successful tame in retail resulted in the mob standing still for a few moments as it went neutral (yellow). In dsp, the mob runs back to its spawn point immediately as it goes neutral (yellow) without any 'stillness'.

hozu: Yes, I agree that would be a good idea to test. Since tame has 10 min cooldown it's probably going to be a long test. How do you suggest I set this up so that I can get good reliable data for use in making this determination. I would like to do it just once, the right way.

**Comment by takhlaq** [comment] 2017-11-22 20:57
iirc we have some issues on dsp with mob name colours from a few years ago which still havent been fixed
im not sure if it was this one https://github.com/DarkstarProject/darkstar/issues/3876 or just something discussed on irc

**Comment by teschnei** [comment] 2017-11-22 20:59
Okay. I designed it so that #1 should work, but I didn't test it. Maybe the
enmity list is adding entries on attack when it shouldn't be (an easy
enough fix, if that's the case). For deaggro, I imagine all deaggro works
the same. If you log out on DSP while being attacked, it probably has the
same problem where the mob immediately starts moving.  That means they
probably need to set roam time on disengage

**Comment by Hozu** [comment] 2017-11-22 21:18
@Wiggo32 The higher the INT difference you get (ie. one set with min INT, another with max INT), the easier it would be to rule out INT being a factor, I think. Ideally it would be nice to figure out what modifies it, but ruling out INT is a good start. Since figuring out how it works would take forever. 10 min cooldown though, ouch.

**Comment by Wiggo32** [comment] 2017-11-22 21:39
I have a lot of gear and a lot of money. I can gear myself with -INT gear as much as possible... conduct a series of 'tame's and record how many success vs fail. Then gear myself with as much +INT gear as possible and do the same for the same number of 'tame's on the same mob. The question is, should the mob be even match so we can accurately guess it's level compared to mine or should it be a little tougher to give a chance for more failures. And how many 'tame's is good enough for analyzing? I know ultimately we should do as many as possible on all types of mobs (Even, Tough, Decent, etc) but I'd like to be able to complete this in a 'reasonable' amount of time which would also be suitable for dsp purposes.

**Comment by Hozu** [comment] 2017-11-22 21:54
I'd think even match would be ideal at first because it wouldn't have any extremes, or any level differences in the calculation. Later tests would be done with different level enemies for getting a better idea of how it actually works, if you want to go beyond just ruling out INT.

I'm more likely inclined to believe it's just a level and Tame modifier (from gear) check if it's so inconsistent that people believe INT modified it. Eh...

**Comment by Wiggo32** [comment] 2017-11-22 22:02
kj: right after this line: https://github.com/DarkstarProject/darkstar/blob/826b9fc5610d837dbdc75fab9202300da874a2c4/src/map/lua/lua_baseentity.cpp#L11313
i added:
```battleEntity->PAI->Reset();```
and it forces the mob to wait a little while before doing anything right after a disengage (tame)

hozu: so -INT, even match mob, 20 tames? and then +INT, same mob, 20 tames? report results? I'm not going to want to do it again after this... im pretty sure i'll be all 'tamed' out. Will that suffice? Tell me if there's anything else I should do before I get started. And I'll include in the results as much info as I can squash into this little window ( exact gear, exact stats, time of day, mob, location, whatever i can think of)

**Comment by Hozu** [comment] 2017-11-22 23:26
I think that would be good enough to rule out dINT, if you can get enough of an INT difference between the two sets. But it would need a lot of INT since with the current Tame script, a 20 INT difference is only 20 accuracy.

**Comment by teschnei** [comment] 2017-11-22 23:31
20 accuracy is 10 hit rate, which isn't that bad really.  Assuming though
that the hit rate isn't already floored or capped.  It should be possible
to get like an 80 or higher differential though. Can you get a single stat
in Abyssea or only all stats?

**Comment by Wiggo32** [comment] 2017-11-23 03:07
I'm coming across lots of gear that increases INT by a great deal +58 just from what is sitting on me now and can get higher by rearranging. Problem is... lots of other stats are increased as well and I don't think that's a good idea. I need to find gear that modifies only INT or as few other stats as possible. I can also make intelligence potions since my alchemy is at 100. So, that's +7 of just regular INT. Not sure about Abyssea, last I been in there I couldn't charm anything it was jug pets only... so I don't know if that means tame doesn't work either or what? So, If you have any good suggestions for gear a 99 bst can wear that modifies only INT and a lot of it... would help. =)

**Comment by Wiggo32** [comment] 2017-11-23 03:53
This is what I got off AH so far: Aquillo's Staff, Ombre tathlum +1, Snow pearl, Shiva ring +1, And Icesoul ring. Together that gives me +30 INT without potion/food and the only other stat modified at all is STR with -4. I'll keep looking though.

**Comment by Wiggo32** [comment] 2017-11-23 05:55
I'm able to get +162 INT in abyssea with gear/atma... however, tame isn't working. "No effect" on the bees or worms as if I tried to tame a yagudo. Outside abyssea, I've got +68 INT with gear/food. Not much on the AH and I'm not sure how much more I can get. INT potions give me medicated effect so that's not really practical for how long they last. Lastly, I need to find someplace that has "Even Match" mobs that are charm/tameable. Best I could find was "Tough" with ffxiwiki reporting 101-102 (Pewter Diremite). Not sure if this is ok since the gap is only 2 lvls or if we can even trust it being it's from ffxiwiki which is the source of the INT modifier for Tame that we are second guessing in the first place. So, with that, I'm done for the night and we'll see if anyone has any ideas which will help in the morning.

**Comment by teschnei** [comment] 2017-11-23 06:44
Ah yeah, Abyssea mobs aren't charmable I guess, so Tame doesn't work on
them.  Not sure on the levelled mobs, I think the guys right outside
Adoulin in Ceizak are fairly low as well, though

**Comment by teschnei** [comment] 2017-11-23 07:19
I've closed this since the original issues are fixed now.  You can keep posting here for the INT tests, but if you do find that INT does nothing, open a new issue for it and I'll change it under that one

**Closed** 2017-11-23 07:18 UTC

**Comment by Hozu** [comment] 2017-11-23 21:14
Tough isn't ideal, but as long as it's not TW or IT it should still work. Rather go higher level than lower level since it's probably easier to notice a difference if the success rate is lower, but not super low.

**Comment by Wiggo32** [comment] 2017-11-24 17:34
Well... 8 hours worth of tame. That sucked. Here we go.

The reason for this test is to determine what effect, if any, INT has on the BST ability 'Tame'.
The initial suspicion is that INT doesn't really make sense as a modifier for 'tame' due to the fact that it is primarily a 'mage-type' stat and that there is little to no gear that a BST can wear which adds bonus' to the INT category.

I went as a 99 BST/49 WHM mostly naked except for the gear used to modify INT. For the initial round, INT was decreased. I used a Versa Celata http://www.ffxiah.com/item/11780/versa-celata and a Versa Hauberk http://www.ffxiah.com/item/11830/versa-hauberk . My stats were as follows:
![negative int](https://user-images.githubusercontent.com/30469395/33218582-ff814a26-d180-11e7-9dc0-06d2357e64b7.jpg)
The target was a "Pewter Diremite" in Rala Waterways (outside of Western Adoulin F-5). The mob checked as "Tough". I was able to use the exact same mob for the entire 8 hours of testing as there was not much traffic by other players in that zone.
The time was 7:15 on Lightningday (New Moon 2%) when the testing began. Here are the first 10 'tames':
1. Success..............6. Success
2. Fail.......................7. Success
3. Success..............8. Success
4. Success..............9. Success
5. Success..............10. Success

From here, the day has changed to Darksday and I wondered at this point if Darksday might have anything to do with the success of 'tame' as it is supposed to influence the success rate of 'Charm' in the same negative fashion. The next 5 'tames':
1. Success
2. Success
3. Fail
4. Success
5. Fail
Not enough to really determine much but I decided to move on to Positive INT and come back and redo the Negative at the end without the influence of Darksday.

For the Positive INT gear, I used: Aquilo's staff http://www.ffxiah.com/item/17548/aquilos-staff Pixie Hairpin +1 http://www.ffxiah.com/item/26696/pixie-hairpin-1 Snow Pearl http://www.ffxiah.com/item/11015/snow-pearl Shiva ring +1 http://www.ffxiah.com/item/27575/shiva-ring-1 Icesoul Ring http://www.ffxiah.com/item/11657/icesoul-ring Santcuary obi http://www.ffxiah.com/item/11765/sanctuary-obi Ombre tathlum +1 http://www.ffxiah.com/item/21362/ombre-tathlum-1 and a Serving of Vermillion Jelly http://www.ffxiah.com/item/5158/vermillion-jelly . My stats were as follows:
![positive int](https://user-images.githubusercontent.com/30469395/33219046-9b4bcfce-d183-11e7-9b83-45e617b84d85.jpg)
Same target, same area, the time for this round of testing was: 2:00 on Firesday (Waxing Crescent 10%). Here are the results:
1. Success.......................11. Success...........................21. Success
2. Success.......................12. Success...........................22. Success
3. Success.......................13. Success...........................23. Success
4. Success.......................14. Success
5. Success.......................15. Success
6. Success.......................16. Success
7. Success.......................17. Success
8. Success.......................18. Fail
9. Success.......................19. Success
10. Success.....................20. Success
I got 3 more because the Vermillion Jelly was still active and I didn't want to just sit around for 30 min waiting for food to wear off. From here, I went back to Negative INT with the exact same setup as the one used initially for Negative INT. The time this time was 8:30 on Iceday (Waxing Crescent 19%). Here are the results:
1. Success.......................11. Success
2. Fail................................12. Fail
3. Success.......................13. Success
4. Success.......................14. Success
5. Fail................................15. Fail
6. Success
7. Success
8. Success
9. Success
10. Success

Conclusion: While my initial suspicion of the insignificance of INT for the BST ability 'tame' was strong, the end results seem awfully coincidental that INT may indeed have something to do with the success rate of 'tame'.  With the first set of results using the Negative INT setup, 3 out of 15 were Failures which equals out to an 80% success rate. With the second set of results using the Positive INT setup, 1 out of 23 was a Failure which equals out to 95.65% success rate. With the third set of results using the Negative INT setup, 4 out of 15 were Failures which equals out to 73.3% success rate. So, from my very minimal testing, it appeared that the success rate for 'tame' was much higher when more INT was applied to the character. 

Suggestion: While the conclusion still may be a coincidence, I suggest that we leave the current tame formula as-is for now and possibly revisit it later when a more extensive and thorough test can be performed.
