### ISSUE TITLE
Dynamis San d'Oria and  Dynamis Bastok mega boss crash

### ISSUE THREAD

**Issue by tourmaline3333** [DarkstarProject/darkstar#6280] opened 2019-11-08 14:25 UTC
**_I have:_**

- [X] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [X] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
0.0.8319

**_Source Branch_** (master/stable) **:** 
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

DSGame-server.exe crashed when I fougnt Dynamis San d'Oria and  Dynamis Bastok mega boss.
Once it crashes,it will crash as soon as mob pop.
but Dynamis Windurst don't crash

I asked DSP forums, but did'nt solve.
plz help me.I want Relic weapon ....

**Comment by wrenffxi** [comment] 2019-11-08 21:29
By "Megaboss" I assume you mean the tier I bosses: Overlord's Tombstone and Gu'Dha Effigy.

On current master branch, I don't have any issue popping and killing these mobs.  Do you have the most recent code compiled, and database built from the most recent SQL?

**Comment by tourmaline3333** [comment] 2019-11-09 02:58
Yes.Megaboss are Overlord's Tombstone(Battlechoir Gitchfotch、Soulsender Fugbrag) and Gu'Dha Effigy

I compiled 0.0.8319 tag on master branch. SQL same.
but part of SQL table "accounts, bcnm_info, conquest_system, server_variables, char_*" over write from  0.0.8318(Self contained installer with my player data).

**Comment by tourmaline3333** [comment] 2019-11-09 03:22
>Once it crashes,it will crash as soon as mob pop.
for example Dynamis San d'Oria, 
spawn 3 mob (Overlord's Tombstone and Battlechoir Gitchfotch and Soulsender Fugbrag),.when trade "Barbaric Bijou" with ???.
Crash as it is appeared. player is never targeted.

I restored SQL database before crash, but not fix

**Comment by vanderleest** [comment] 2019-11-24 04:07
On a fresh build of the current master branch, this appears to be caused by any mob with the spell Death (spell id 367) due to the ways the ignore shadows flag was done. See #6025 and #5954 

As a temporary solution, I adjusted mob_spell_lists so that either mobs don't have access to 367 or gave them another spell.

I assume you could also temporarily adjust spells/death.lua by commenting out `spell:setFlag(dsp.magic.spellFlag.IGNORE_SHADOWS)` until the flag has been added. I didn't test this solution.

**Comment by TeoTwawki** [comment] 2019-11-24 05:24
woops, I kinda forgot about that when Isotor vanished off the face of the earth on me..

**Comment by TeoTwawki** [comment] 2019-11-24 05:37
> I assume you could also temporarily adjust spells/death.lua by commenting out spell:setFlag(dsp.magic.spellFlag.IGNORE_SHADOWS) until the flag has been added via the spellFlag branch. I didn't test this solution.

yes. I recommend that until the fix is in.

**Closed** 2019-11-24 17:21 UTC
