### ISSUE TITLE
Crash when sending PartyEffects packet

### ISSUE THREAD

**Issue by whasf** [DarkstarProject/darkstar#2239] opened 2015-10-11 15:05 UTC
https://www.dropbox.com/s/beslwpkf3bjl5m1/GS_10-11-2015_08-18.7z?dl=0

**Comment by xdemolish** [comment] 2015-10-11 15:33
dumping on kayjay cause what even is a corrupted heap

**Comment by xdemolish** [comment] 2015-10-11 15:36
duplicate of https://github.com/DarkstarProject/darkstar/issues/2219

**Closed by xdemolish** 2015-10-11 15:36 UTC
Labels: Dump
