### ISSUE TITLE
Getting a lot of "Playername cannot perform that action."

### ISSUE THREAD

**Issue by xipies** [DarkstarProject/darkstar#2855] opened 2016-03-04 05:32 UTC
**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
180c791

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
For example, when trying to use magic or ranged attack on machines in Ghelsba Outpost. They're now only hittable (by melee) at the very edge. Cannot pull them to ledge with magic or ranged attack. Another example: Several places in Tahrongi Canyon esp where a mob is at a small ledge. You now have to go all the way around to where there is no impassable terrain between you and the mob.

It feels like there is terrain that is marked as if it is a complete vertical wall, rather than "can't walk over this in one direction, but can see over it."

**Comment by xdemolish** [comment] 2016-03-04 05:35
duplicate of https://github.com/DarkstarProject/darkstar/issues/2837

**Closed by xdemolish** 2016-03-04 05:35 UTC
