### ISSUE TITLE
NMs and PH not respawning

### ISSUE THREAD

**Issue by nyczducky** [DarkstarProject/darkstar#3663] opened 2017-01-23 15:58 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) 30161227_1

**_Server Version_** (type `@revision` in game) ff73311

**_Source Branch_** (master/stable) master

**_Additional Information_** (Steps to reproduce/Expected behavior) Notorious monsters and their PH are not respawning. It seems that this happens randomly after a few kills and then affects a majority of NMs with a server restart being the only way to correct this.

Seems to occur on NMs with PH lottery pops and timed spawns with PH as the PH will not respawn.

I know that's really not that helpful. If there is any data I could provide, please let me know.

**Comment by wrenffxi** [comment] 2017-01-23 18:50
Have you got some NMs you know for sure this happens on, that could be used for testing?  Thanks!

**Comment by nyczducky** [comment] 2017-01-23 18:50
Leaping Lizzy, VE, and Argus.

**Comment by nyczducky** [comment] 2017-01-23 19:05
I see another issue open for incorrect NPC IDs being shared. 

This was also happening before the November update. So unless the NPC IDs were screwed up a while ago, I don't think it's related. I'll run around on retail capturing the NPC IDs in the zone to see if it is an issue.

**Comment by ibm2431** [comment] 2017-01-23 21:55
@nyczducky Do you have a link to the issue for "incorrect NPC IDs being shared"? There's one about mobs sharing group IDs. But NPCs/mobs literally can't share the same ID because the SQL import would reject the duplicate primary key.

**Comment by nyczducky** [comment] 2017-01-24 04:47
#3658

**Comment by TeoTwawki** [comment] 2017-01-24 09:16
not related. thats group IDs and its almost entirely campaign stuff and other unimplemented or obscure content involved.

I did some status printing of mobs involved. I don't see ho its happening but some mobs are getting stuck in status 16, when they should be status 0.

**Comment by nyczducky** [comment] 2017-01-24 17:54
https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Valkurm_Dunes/MobIDs.lua#L15

Comma after last array element? Would that cause the issue?

**Comment by Brierre** [comment] 2017-06-22 18:20
I'm starting to have this issue as well.  It's almost like DeterMob works TOO well and never stops deterring!  

For instance: 

1. I kill LL PH, and LL pops. 
2. Then I kill LL, and the PH that just popped LL never comes back.  In the instance of LL, there are other PH, so you wouldn't notice as readily, but in the case of other mobs (Herbage Hunter, for example, who has only one PH) this would prevent HH from being popped.  Unless server is restarted...

I have another question regarding this PH/POP code.  To what does the os.time(t) refer to--as opposed to just os.time( )?  Most of these older NM have os.time(t) and Wren said we try to use os.time( ) now.

**Comment by teschnei** [comment] 2017-06-22 18:48
os.time(t) and os.time() do the same thing (passing in a table makes the time from the table, but those are all passing in nil, so it's just the same thing)

**Comment by TeoTwawki** [comment] 2017-06-22 19:26
I got distracted and kj beat me to posting, decided to hit comment button anyway.
if the argument t is passed, you get a table returned instead of raw time returned. 

```c
static int os_time (lua_State *L) {
  time_t t;
  if (lua_isnoneornil(L, 1))  /* called without args? */
    t = time(NULL);  /* get current time */
  else {
    struct tm ts;
    luaL_checktype(L, 1, LUA_TTABLE);
    lua_settop(L, 1);  /* make sure table is at the top */
    ts.tm_sec = getfield(L, "sec", 0, 0);
    ts.tm_min = getfield(L, "min", 0, 0);
    ts.tm_hour = getfield(L, "hour", 12, 0);
    ts.tm_mday = getfield(L, "day", -1, 0);
    ts.tm_mon = getfield(L, "month", -1, 1);
    ts.tm_year = getfield(L, "year", -1, 1900);
    ts.tm_isdst = getboolfield(L, "isdst");
    t = mktime(&ts);
    setallfields(L, &ts);  /* update fields with normalized values */
  }
  if (t != (time_t)(l_timet)t || t == (time_t)(-1))
    luaL_error(L, "time result cannot be represented in this installation");
  l_pushtime(L, t);
  return 1;
}
```



*And I still have no idea how occasionally an NM or PH will at random be stuck in the wrong status value*. I haven't been able to consistently reproduce the issue on any one NM, but whenever one does get stuck (happens maybe once in a thousand mob kills) I check and its status value is wrong.

**Comment by Brierre** [comment] 2017-06-22 19:33
Thanks, guys!  I'll keep trying and see if I can't find a pattern, but it is perplexing. :(

**Comment by teschnei** [comment] 2017-06-22 19:33
> if the argument t is passed, you get a table returned instead of raw time returned.

you always get the raw time returned (you're thinking of os.date, probably).  The table is used as input if it exists instead of using time(NULL).  you can see in the implementation you posted that it always pushes the time_t in either path, and sets the time_t's fields from the table if it's not nil

**Comment by teschnei** [comment] 2017-06-22 19:38
however, it's worth noting that if the argument is not nil but isn't a table (or is a table without the time fields), the time you will get is going to be totally wrong.

so it's very possible that something is creating a global var "t", and the older os.time(t)'s are using it and getting bogus times.  It'd be a good idea if we removed all of the os.time(t)'s that are supposed to be os.time().

**Comment by TeoTwawki** [comment] 2017-06-22 19:38
_- shrug -_ distracted posting

**Comment by TeoTwawki** [comment] 2017-06-22 19:39
I can mass do that right now I guess

**Comment by TeoTwawki** [comment] 2017-06-22 19:48
e69adb29178698ab3bf7cd0c3ef5a0f71764ccfe

**Comment by TeoTwawki** [comment] 2017-06-27 23:02
So today I noticed our MobIDs.lua may have the same problems (and solutions) as our TextIDs.lua

It makes it possible to have the variables for the NM you are after to be nil, if I am not mistaken. If I am wrong then I guess all zones wind up together in 1 big pile of mob IDs over time.

Might be a reason why when I go to test these NMs all work fine for me yet they do indeed seem to stop working later, at random.

**Comment by ymkc** [comment] 2017-08-14 22:10
Concerning the multi PH NMs, I think there is nothing to prevent being "lucky" on more than one PH.

**Comment by TeoTwawki** [comment] 2017-09-25 23:00
Think @Wiggo32 may have figured it out. 

Can use this command to check mobs status flags value:

```
!exec GetPlayerByName("<me>"):PrintToPlayer(string.format("Status: %d",GetMobByID(mobidhere):getStatus() ))
```

What we think happened is multiple PH's got "deter /dissalowRespawn" on them, and the NM only clears one. A check is being added to ensure only one PH gets flagged to not repop.

**Comment by davismj** [comment] 2018-03-02 08:08
I dunno if its related, but if I kill Leaping Lizzy and then log out, provided no one else enters the zone, when I log back in the placeholder will not have respawned.

**Comment by wrenffxi** [comment] 2018-03-02 19:51
The previous issue with multiple PHs getting disallowRespawn() is fixed by using the phOnDespawn() function in globals/mobs.  We've been moving all the lottery NMs over to this code, including Leaping Lizzy, so that should no longer be a problem.

The issue davismj is describing is unrelated, but true.  If you kill a mob, then log out before it fully despawns, and nobody else is in the zone, the zone tick that would despawn the mob never happens, so the NM's onDespawn() code doesn't run while the zone is empty.  However, I think it will run as soon as any player enters the zone.  So in the example davismj gives, I would expect the PH to reappear ~5 minutes after he logs back in, or whatever the Rock Lizard respawn time is.

**Comment by dwn134** [comment] 2018-03-02 20:46
On this new code do you actually have to go and kill a placeholder to get the timer to start counting or does the counter start as soon as server is on?

**Comment by wrenffxi** [comment] 2018-03-02 22:27
On server restart, all cooldowns are reset, so killing any placeholder has a chance at popping its lottery NM.

**Comment by kamajii7** [comment] 2018-03-02 23:08
I think I found out the issue with Leaping Lizzy. It looks like one of the place holders is not linked to Leaping Lizzy. I lost my VM / Server so I cannot verify if the fix works, it will be some time before I have enough time do do that. I have a feeling this is why we are having inconsistant results for LL. If you killed the "correct" place holder everything works, if you didn't then LL would never get reset. Like I said I am not able to test, and someone please correct me if I am wrong in thinking these should be the same ID. 

https://github.com/DarkstarProject/darkstar/blob/f817903b03c359c39498754df3c7172628681a48/scripts/zones/South_Gustaberg/MobIDs.lua

```
LEAPING_LIZZY_PH =
{
    [17215867] = 172158**6**8, -- -275.441 20.451 -347.294
    [17215887] = 172158**8**8, -- -322.871 30.052 -401.184
}
```

**Comment by TeoTwawki** [comment] 2018-03-02 23:10
@kamajii7 
There have been changes since this issue was opened. LL is working fine now and the only reason this isn't closed is we still have more NM's to convert to the new system

**Comment by wrenffxi** [comment] 2018-12-24 22:38
we can probably close this now. i don't think there are lottery NMs using the old system anymore (just a bunch of lottery NMs that haven't been added yet)

**Closed** 2018-12-24 22:39 UTC
