### ISSUE TITLE
Character "g" appears at the end of server message.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#2706] opened 2016-01-31 12:29 UTC
Minor issue, but annoying non the less. No matter what text you enter for the server message; around 80% of the time a "g" will appear after it when viewed in-game. Not sure if there is a specific condition causing it.

In this example, I have only a space for the server message (as no server message causes a crash).

![x1](https://cloud.githubusercontent.com/assets/7009763/12702114/371eb4a8-c816-11e5-82fc-3a28d734943d.png)

**Comment by dickeyf** [comment] 2016-01-31 15:25
This is caused by having extra line at the end of that file.

**Comment by TeoTwawki** [comment] 2016-01-31 23:25
> This is caused by having extra line at the end of that file.

Incorrect. it has to do with the length of the message and the length calculation for it in the server not matching up. I've previously reported this issue along with others. #1510

**Comment by teschnei** [comment] 2016-02-01 07:18
Closing in favor of #1510

**Closed by teschnei** 2016-02-01 07:18 UTC
