### ISSUE TITLE
Crafting HQ Tier. 

### ISSUE THREAD

**Issue by Leelink1** [DarkstarProject/darkstar#1644] opened 2015-07-01 12:17 UTC
Seen a few complaints about the HQ tier rates in crafting. Did some investigation and enabled the debug on synthutils.cpp and found the following. 

If i have Smithing lvl 14. And im trying to make Bronze Dagger HQ which is a lvl 3 synth. i have a synth difference of -11. This puts me in the HQ Tier 2. Works fine

If i try Crafting the same thing again on Lightsday however my synth difference becomes -12 and im more closer to the HQ Tier 3 rate. This isn't working because trying to HQ a synth on Lightsday should lower ur chances and should in put me at -10 and reduce my HQ Tier to 1
![crafting screenshot](https://cloud.githubusercontent.com/assets/12517352/8453829/2d6212da-1ff0-11e5-8b46-179bfb9c37fd.png)

If i try crafting the same thing on Darksday. my Synth difference becomes -10 and puts me in the HQ Tier 1 rate. Again this isn't what it should be because Darksday should put my difference to -12 which should me closer to the HQ Tier 3 Rate.
![crafting screenshot2](https://cloud.githubusercontent.com/assets/12517352/8454077/6b1fc2b4-1ff2-11e5-872d-7d079860653b.png)

The Same can be said for the Moon Phase as well. When the moon is full it should decrease my HQ rate. Instead it increases it. And when its a new moon it should increase my HQ rate. instead it decreases it. 

It looks from my eyes that the issue is not separating crafting into 2 parts. 

For the Synth Difficulty it works fine if your going for a normal success rate. However if you wish to HQ a item it currently using that same Difficulty from Normal success rate when it should be using its own system separate system.

Hope that makes sense.

**Comment by Deadwing888** [comment] 2015-07-02 10:49
I think the terminology for your tiers is off.

0-10 = T0 = ~1% hq rate
11-30 = T1 = ~10% hq rate
31-50 = T2 = ~25% hq rate
51+ = T3 = ~50% hq rate

What's at the heart of the issue is that lightsday/darksday and moon phases are having a direct effect on skill level when they shouldn't (at least not in a way that factors into hq tiers).

On the subject of crafting in general the day/moon/direction on darkstar have a much bigger effect on crafting hqs and skillups than they did on retail. The T1 hq rate is also higher than it should be by a few %. Oh and one last thing, I personally never got anything higher than a .1 skillup skilling from 60-100.

If anyone needs me to parse some crafts on retail let me know.

**Comment by Leelink1** [comment] 2015-07-02 11:43
What's at the heart of the issue is that lightsday/darksday and moon phases are having a direct effect on skill level when they shouldn't (at least not in a way that factors into hq tiers). 

Completely agree with this. Maybe just make it so its a factor of Your Skill level (with gear and buff's) vs the Synth level for HQ. Since the chance is effected by the right values later on. 

Also these are the HQ% tier rates
case 4:  chance = 0.500; break;
						case 3:  chance = 0.300; break;
						case 2:  chance = 0.100; break;
						case 1:  chance = 0.015; break;
						default: chance = 0.000; break;

**Comment by TeoTwawki** [comment] 2015-07-02 14:23
There are also settings to enable/disable things like moon from even mattering, but I think those might only effect synth success rate and not HQ, not sure. If they don't, they should.

**Comment by maxtherabbit** [comment] 2015-07-06 14:03
teo is correct, there is a setting to turn on/off moon phase and weekday being factored in the synth difficulty calculation

if they are switched 'on' they are used to calculate difficulty - the exact same formula for difficulty is used to determine success rate as well as HQ tier, this is intended behavior

if they are switched 'off' they are not used to calculate difficulty in either case

regardless of the config setting, they *are* used to apply a separate penalty/bonus to HQ rate which is applied after the hq tier is determined

again this is intended behavior, based on information I was able to research from retail regarding HQ rate

it sounds to me that the 'bug' you are describing would be resolved in your case by simply turning the day/moon matters settings to 'off'

**Comment by maxtherabbit** [comment] 2015-07-06 14:06
perhaps better data from retail is available now than when I last researched the topic, in which case I'd be happy to review it

but the problem with crafting is you talk to 10 different retail crafters and they all give different answers, yet they all know exactly how it works

**Comment by Leelink1** [comment] 2015-07-06 14:22
The seprate penalty bonus works fine.
I just think that Synth difference in the HQ section needs a different formula which just looks at the skill you have (+gear and buff) and the skill of the craft. .

**Comment by maxtherabbit** [comment] 2015-07-06 14:26
I don't mean to be rude, but you have to realise this is a hotly contested topic. Unless you have concrete testing from retail I'm not going to change it based simply on how you think it should work.

**Closed** 2015-07-06 14:43 UTC
Labels: Crafting / Fishing
