### ISSUE TITLE
CoP Ouryu Fight after win, repeated "called another event"

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#3464] opened 2016-10-16 00:40 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30161004_1

**_Server Version_** (type `@revision` in game) **:**

67f33da
**_Source Branch_** (master/stable) **:**

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
After winning BCNM, it sent us into a loop where it gives us the exp for the fight. When we tried to select Yes/No to skip CS it sent us back into that loop (allowing for a real easy meripo party ^^). Only way to stop it is to force crash client.

**Comment by wrenffxi** [comment] 2016-10-16 14:08
I've seen the same issue happen when winning LB5 Maat fight.  Seems to happen in battlefields that can be won while a foe has remaining health.

**Comment by Brierre** [comment] 2016-10-16 23:07
I think this is the same issue, fixed back in March?  https://github.com/DarkstarProject/darkstar/issues/2875

**Comment by Fizztastic** [comment] 2016-10-16 23:51
This is a duplicate of https://github.com/DarkstarProject/darkstar/issues/3344 but and it hasn't been fixed. The fix I've temporarily implemented on my server is just to comment out this line https://github.com/DarkstarProject/darkstar/blob/master/scripts/zones/Monarch_Linn/bcnms/savage.lua#L48.

**Closed** 2016-10-17 00:15 UTC
