### ISSUE TITLE
Antlion Trackers linking with Xolotl 

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2772] opened 2016-02-18 16:53 UTC
Ls mates told me that underground antlions are linking with Xolotl and are untargetable.

**Comment by LOLTHF** [comment] 2016-02-19 15:05
There are actually 2 separate bugs.

First, antlions link with Xolotl. Mainly the above-ground ones near his spawn and can be annoying, but if you drag him near any antlions they all link with him. Really strange, they're completely different mob families.

Second bug: the underground antlions such as cave antlions near tiamat behave like untargetable worms. They follow you around underground and constantly attack you but cannot be targeted in any way.

Drop rate on knife is correctly functioning however ^_^. Completely nonexistant! Truly perfectly simulating retail!

**Comment by Fiocitrine** [comment] 2016-02-20 01:16
Yeah, sorry for the confusion. And the dagger drop rate is poop. Retail as usual!

**Comment by Deadwing888** [comment] 2016-02-20 05:57
Duplicate of #2392

**Closed** 2016-02-20 07:07 UTC
