### ISSUE TITLE
Promyvion-Dem Portals not working

### ISSUE THREAD

**Issue by Fiocitrine** [DarkstarProject/darkstar#2690] opened 2016-01-29 04:40 UTC
When you kill a Memory Recepticle and the portal appears, occasionally when you warp from area to area, the client crashes. This has been confirmed by two players on the same server.

**Comment by aizenmyou** [comment] 2016-02-02 18:57
I haven't noticed crashing, but all of the Promy randomly cause a few members of the party to get stuck in a black screen to which a GM has to move them to a member that's not stuck.

**Comment by wrenffxi** [comment] 2019-01-28 23:37
This can probably close.  The blackscreening -is- still a problem AFAIK, but it's a duplicate of #2327.  I haven't seen or heard of the event causing a full client crash, however, with latest client + portal code.

**Comment by TeoTwawki** [comment] 2019-01-28 23:40
old as F ticket, make new one if issue happens again

**Closed by TeoTwawki** 2019-01-28 23:40 UTC
