### ISSUE TITLE
Problem zillart mission. - end of the mission 4 (CS)

### ISSUE THREAD

**Issue by AlexandreCA** [DarkstarProject/darkstar#1432] opened 2015-05-14 07:40 UTC
Hey, I give again the bug discovered by me. I test that Linux and Windows, so.. The problem is not me. After have killed the tomberry x3, you have a CS. The problem is when the CS cut and create a black screen.

**Comment by Desufire** [comment] 2015-05-16 12:03
#1425
I reported this. They're looking into it. I posted a work around I found worked at the sacrifice of a CS.

**Comment by xdemolish** [comment] 2015-05-16 13:49
duplicate of #1425

**Closed by xdemolish** 2015-05-16 13:49 UTC
