### ISSUE TITLE
When the target player-character evades an AoE TP move; all other possible targets also evade it.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1203] opened 2015-03-31 23:09 UTC
Tested this with Spike Flail; if the original target evades - an entire alliance of 18 also evades.

This may also likely applies to all other TP moves.

**Comment by ashdam** [comment] 2015-03-31 23:17
Nice bug!

**Comment by bendangelo** [comment] 2015-04-02 14:45
I'll take a look at this. Does this only effect alliances?

**Comment by teschnei** [comment] 2015-04-02 14:50
no, everyone

**Comment by xdemolish** [comment] 2015-04-06 15:40
duplicate of https://github.com/DarkstarProject/darkstar/issues/1194

**Closed by xdemolish** 2015-04-06 15:40 UTC
