### ISSUE TITLE
Client Crash on Skills being interrupted by mob death

### ISSUE THREAD

**Issue by abriasffxi** [DarkstarProject/darkstar#3446] opened 2016-10-12 19:35 UTC
**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160831_1

**_Server Version_** (type `@revision` in game) **:**
b94cc2bbed3650b03fe

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Client sometimes crashes when weaponskills are interrupted.  Client ALWAYS (or almost always) crashes when summoner TP moves are interrupted by mob death.  Easily reproducible with summoner.

Let me know if there's any debugging I can help with.  The server log doesn't show anything but xiloader.exe crashes.

**Comment by teschnei** [comment] 2016-10-12 20:00
Don't we have an issue for this already

**Comment by abriasffxi** [comment] 2016-10-12 20:04
I didn't see it, but the one where animations are causing errors in OhShi and the animations being messed up might be related?

**Comment by teschnei** [comment] 2016-10-12 20:07
Are they not he exact same cause?

**Comment by teschnei** [comment] 2016-10-12 20:07
duplicate of #3393

**Closed by teschnei** 2016-10-12 20:07 UTC
