### ISSUE TITLE
The spell Stun is not accurate enough; conversely the spell headbutt has 100% stun accuracy.

### ISSUE THREAD

**Issue by Deadwing888** [DarkstarProject/darkstar#1609] opened 2015-06-20 06:26 UTC
A level 75 rdm/drk should have no trouble landing stun on things like cerberus, tiamat, vrtra, etc. 

On a darkstar sever it takes a ton of magic accuracy gear to land at all, and no matter what you do it won't land reliably.

There are some places stun should get resists (for example Dynamis Lord) and some mobs are immune (for example King Behemoth) but in general it should land when you cast it and it currently does not.

The stun off the blue magic spell Headbutt will currently land 100% of the time leading to oddities like RDM/BLU being used for chainspell headbutt stunlock. Headbutt should not be a reliable source of stun at the hnm level. I'm not sure how accurate it should be, but I believe it's accuracy is based off the skill level of the of the main handed weapon as well as blue magic skill.

**Comment by Kthulupwns** [comment] 2015-06-22 07:58
I submitted a similar issue like this not too long ago as well.

**Comment by xdemolish** [comment] 2015-06-22 08:01
duplicate of https://github.com/DarkstarProject/darkstar/issues/1526

**Closed by xdemolish** 2015-06-22 08:01 UTC

**Comment by TeoTwawki** [comment] 2015-06-23 10:01
@Deadwing888 I added a resist check to headbutt recently, but it needs someone with a good knowledge of how often it should land to adjust the resist value at which a resist will actually trigger. All the skill checks etc are there now, so it should just take tweaking the value to get it retail now.

**Comment by Deadwing888** [comment] 2015-06-28 06:34
Okay, if it's nobody has gotten to it in two weeks or so I'll hop on retail and see what I can figure out. Thanks!
