### ISSUE TITLE
Targe Beetles incorrectly aggressive

### ISSUE THREAD

**Issue by davismj** [DarkstarProject/darkstar#4581] opened 2018-02-22 11:32 UTC
**_I have:_** rip

- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30171205_0

**_Server Version_** (type `!revision` in game) **:** b42e....bc47

**_Source Branch_** (master/stable) **:** 

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

http://ffxiclopedia.wikia.com/wiki/Targe_Beetle

**Comment by pandorraffxi** [comment] 2018-02-22 15:45
What is incorrectly aggressive about them? Sight? Sound? Smell? Musk?

**Comment by davismj** [comment] 2018-02-22 15:45
I walked by and they addressed me by the wrong gender pronoun.

**Comment by pandorraffxi** [comment] 2018-02-22 15:47
So...by sight?

**Comment by davismj** [comment] 2018-02-22 16:35
Yes, aggressive by sight.

**Comment by pandorraffxi** [comment] 2018-02-22 16:45
According to Wiki, its aggressive to sight. don't have a retail account, but I think its working as intended.

**Comment by Wiggo32** [comment] 2018-02-22 17:28
![targebeetle](https://user-images.githubusercontent.com/30469395/36553896-33ba4c56-17c3-11e8-93a5-5270781b3cb3.jpg)

My 64 BLM on retail says that they don't aggro... from sight nor sound or noisy clown.

**Comment by TeoTwawki** [comment] 2018-02-22 17:39
> According to Wiki, its aggressive to sight.
.

> My 64 BLM on retail says that they don't aggro

ShitWikiSays™ strikes again

**Comment by TeoTwawki** [comment] 2018-02-22 17:48
Just checked and pretty much every high level beetle is using pool 689 chamber beetle stats. So probably more of them with things wrong.

**Comment by davismj** [comment] 2018-02-23 01:04
Wiki says link by sight, non-aggressive. Which is correct, I believe.

![image](https://user-images.githubusercontent.com/3845823/36572769-ed45a644-1880-11e8-8721-886d4b983208.png)

http://ffxiclopedia.wikia.com/wiki/Targe_Beetle

**Comment by TeoTwawki** [comment] 2018-02-23 03:13
Aww, ShitWikiDidn'tSay just doesn't have the same ring to it :(

**Comment by TeoTwawki** [comment] 2018-02-23 03:15
Anyway we just need to use another pool without agro flag for beetles that don't agro. Instead of all beetles assumed chamber beetle clones, heh

**Comment by davismj** [comment] 2018-05-09 11:57
Deviling Bats as well.

http://ffxiclopedia.wikia.com/wiki/Deviling_Bats

**Comment by TeoTwawki** [comment] 2018-05-15 23:59
the solution is new pools, new pools everywhere

![image](https://user-images.githubusercontent.com/6871475/40089576-5f076d10-587a-11e8-93fc-a7a1ea10c1ae.png)

**Comment by davismj** [comment] 2018-06-03 14:36
Poroggo Excavator started casting Quake...

http://ffxiclopedia.wikia.com/wiki/Poroggo_Excavator

**Comment by wrenffxi** [comment] 2019-07-21 03:05
Can close this issue.  Bats and Beetles fixed in recent PRs.  Will get to Poroggos eventually.  I'm working through the entire bestiary.

**Comment by TeoTwawki** [comment] 2019-07-21 17:05
Ty  wren!

**Closed** 2019-07-21 17:05 UTC
Labels: Easy Fix
