### ISSUE TITLE
Shadow effects or Blink effects bug

### ISSUE THREAD

**Issue by Kthulupwns** [DarkstarProject/darkstar#1515] opened 2015-06-04 09:04 UTC
Whenever a mob uses a TP skill of any Kind that would take 1-4 shadows but doesn't deal any damage to the player, the player loses 1 hp. I know it seems like an insignificant issue, but longer fights can make that HP lost matter. Not even sure where to begin with this.

**Comment by maxtherabbit** [comment] 2015-06-25 22:10
is the HP actually dropping or is it possibly just the log message showing 1?

**Comment by xdemolish** [comment] 2015-07-03 00:27
duplicate of https://github.com/DarkstarProject/darkstar/issues/1213

**Closed by xdemolish** 2015-07-03 00:27 UTC
