### ISSUE TITLE
Level Sync is being applied to players in a different zone than the target syncee.

### ISSUE THREAD

**Issue by dazusu** [DarkstarProject/darkstar#1087] opened 2015-03-16 23:28 UTC

**Comment by Djcocha** [comment] 2015-03-16 23:39
Not sure if same issue but when this happens and you zone into the zone with the syncee you do not get sync effects. Like if you are lvl 75 in zerun & sync to lvl 25 in korroloka and then zone into korroloka you will not get GoV page credit or any exp for any mob that you touch.

**Comment by xdemolish** [comment] 2015-03-17 12:46
couldn't reproduce bug, closing for now

**Closed by xdemolish** 2015-03-17 12:46 UTC
