### ISSUE TITLE
Seekers of Adoulin mobs are not the right level.

### ISSUE THREAD

**Issue by wadski** [DarkstarProject/darkstar#1875] opened 2015-08-05 11:29 UTC
Hey, i just set up my server last week and i noticed that all mobs in SoA zones check too weak to level 99 characters. Ive played on some servers were we could merit there, and was wondering how i could change this if its in the db or if it was a custom setting? 

Sorry if this is the wrong place to post. Just looking for a solution =)

**Comment by teschnei** [comment] 2015-08-05 13:44
settings.lua, NORMAL_MOB_MAX_LEVEL_RANGE_MIN/MAX

**Comment by wadski** [comment] 2015-08-05 14:09
Thx I tried to change the value to default and I couldn't start the server up I'll check it out    Does this affect abyssea also?

Sendt fra min iPhone

> Den 05 Aug 2015 kl. 15:44 skrev Tyler Schneider <notifications@github.com>:
> 
> settings.lua, NORMAL_MOB_MAX_LEVEL_RANGE_MIN/MAX
>

**Comment by teschnei** [comment] 2015-08-05 14:13
Yes. Set it to 200 or something and that should be fine

**Comment by wadski** [comment] 2015-08-05 14:57
Thanks alot! should i set min level range to anything? or just leave it at 81?

**Comment by teschnei** [comment] 2015-08-05 15:21
Same thing, set it to like 200. Or else mobs will spawn with a level range
of like 81 to 100+

**Comment by wadski** [comment] 2015-08-05 15:26
Gotcha! Thanks again for the help it all works now =)

**Comment by Samanet** [comment] 2015-08-05 16:00
hey! have same issue
in settings.lua
NORMAL_MOB_MAX_LEVEL_RANGE_MIN = 200; 
NORMAL_MOB_MAX_LEVEL_RANGE_MAX = 200; 

error msg in dsgame-server is invalid min and max arguments for uniform_int

**Comment by teschnei** [comment] 2015-08-05 16:08
Sorry, do 199 min and 200 max for now

**Comment by wadski** [comment] 2015-08-05 16:15
i set my min at 100 and it worked

**Comment by Samanet** [comment] 2015-08-05 16:16
still not work for me..
the old dsgame-server (vs2013 build) is fine to me ,

**Comment by teschnei** [comment] 2015-08-05 16:27
The new rng has nothing to do with vs2015, just happened to be implemented
at the same time. Either way, I can't help you if you use an old build

**Comment by teschnei** [comment] 2015-08-06 00:09
I pushed an update that fixes having the level range as the same and the level range being off by 1 - so 200/200 and 199/200 should both work now

Either way, closing because the problem is resolved

**Closed by teschnei** 2015-08-06 00:09 UTC
