### ISSUE TITLE
Players can get stuck on BCNM win sometimes

### ISSUE THREAD

**Issue by Hozu** [DarkstarProject/darkstar#2875] opened 2016-03-07 17:20 UTC
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160203_0

**_Server Version_** (type `@revision` in game) **:**
https://github.com/DarkstarProject/darkstar/commit/2643851f28ef33e4ab1c5d1fdcaf0e98ba268bb4
Edit: Still a problem on https://github.com/DarkstarProject/darkstar/commit/023899f5cf50edd772ca9b1e1249057b0314c7a0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Sometimes no CS plays, and dead players are unable to home point or be raised/tractored. Sometimes you get the win credit from onEventFinish despite the event never playing, but not always. Not sure if it always happens or what, but I've been getting many, many reports about this.

**Comment by bendangelo** [comment] 2016-03-07 18:41
They should be moved to the exit with other players.

**Comment by Hozu** [comment] 2016-03-07 18:53
Yeah on retail, I vaguely remember that dead people stand up on win, while the CS loads, CS plays, then when it's all done, they fall over as soon as they would regain control.

**Comment by Hozu** [comment] 2016-03-07 19:46
Actually, it seems that anyone can get stuck, alive or dead. But the dead get stuck worse.

**Comment by ZirkPrime** [comment] 2016-03-09 00:16
Seems related to #2816, that issue doesn't provide any other info though. Which BCNM's are people reporting getting stuck in? (I'm guessing a bunch were 5-1)

**Comment by Hozu** [comment] 2016-03-09 00:37
I've had reports of various BCNMs, 2-3, 5-1, 5-2, and probably more. Not the Prime fights, surprisingly. Maybe it's because only one person went in?

**Comment by ZirkPrime** [comment] 2016-03-09 00:45
All of the BCNMs you named have the property of being tied to a nation specific questline, yet entry can still be granted to people on the same mission yet from a different nation. For example, if a Sandy person is the first person to click the door and initiate the Shadow Lord fight, their dialogue box will show them entering "The Shadow Lord", whereas a Bastok person enters "Xarcabard, Land of Truths".  That could be tripping things up in certain cases. I suspect a party of all Bastok people doing "Xarcabard, Land of Truths" won't reproduce.

**Comment by ZirkPrime** [comment] 2016-03-09 01:17
If that turns out to be wrong, then a broader pattern could be the presence of "helpers", people who have completed a quest/mission but are helping people currently on that mission. For the Avatar Prime fights, no helpers are permitted, everyone must have the appropriate, identical quest flagged in order to gain entry, so there can be no mismatch. ENM's (i.e. to get a hagun drop) enforce a similar policy.

**Comment by Hozu** [comment] 2016-03-09 01:25
I'm more likely inclined to believe that it has to do with the helpers than anything.

**Comment by mhk4g** [comment] 2016-03-13 07:31
Happened twice today on Windurst 2-3 in Waughroon Shrine. Both times all 3 players have mission, all 3 survive, fades permanently to black after victory with no credit. This is on "LM's Project Darkstar server", @revision "Unknown" so take it with a grain of salt, but client version matches Hozu's.

**Comment by Hozu** [comment] 2016-03-21 14:45
Someone got this as of https://github.com/DarkstarProject/darkstar/commit/023899f5cf50edd772ca9b1e1249057b0314c7a0 : http://i.imgur.com/KZyljcT.jpg

**Comment by Hozu** [comment] 2016-03-24 01:28
Someone else managed to get the same CS to play over and over, and since it was a CoP fight, they were able to get EXP repeatedly.

**Comment by Hozu** [comment] 2016-04-06 19:09
Also got a couple of reports with BCNMs that end before the mob dies, the mob remains and beats the shit out of players in the CS.

**Comment by helixhamin** [comment] 2016-04-07 01:36
@Hozu Sadly, I have noticed this with every CS where mobs are around and agg. For example, when I go to turn in my dragon egg for DRG, the weapon right next to the ??? likes to agg my toon, and I leave the CS dead. The only way I have found to counter this is to trigger godmode...

**Comment by Hozu** [comment] 2016-04-07 01:40
Well in BCNMs the mobs are supposed to be removed on win. :P

**Comment by Hozu** [comment] 2016-04-30 20:07
This issue seems to be tied to certain BCNM fights. People don't have an issue with any of the CoP mission fights, but they do for maat mostly. Sometimes nation 5-1, more rarely nation 2-3.

I think certain jobs (ie. arenas/BCNM fights) get stuck on "Another event has been called (etc.)" which gives them the onEventFinish stuff, others the BCNM fight never ends despite Maat being defeated.

**Comment by hookstar** [comment] 2016-05-02 20:43
I can confirm what Hozu said above. Did Maat and get stuck in the Another event being called loop, went directly to Chamber of Oracles fight and was able to progress. Fresh pull of DSP from last night.

**Comment by nesstea** [comment] 2016-05-04 17:20
Did the summoner Maat fight on multiple yesterday's build. Worked fine until you win. Got stuck on a black screen.

**Comment by eraffxi** [comment] 2016-07-10 21:05
still an issue

**Comment by nyczducky** [comment] 2016-07-28 15:51
Confirmed still an issue. Any and all BCNM fights have the chance to do this. 

Being in a party or not, first timers or with helpers, same or different nations, etc does not matter.

-70 SAM Maat, black screen on win, did not complete quest.
-Mission 5-1 with alt from same nation in group. Both first time doing the mission. One character got clear other didn't. Both characters ended up in black screen with mobs hitting us and unable to do anything. Timer continues. Terminated process and tried 3 times until alt received key item.
-AF3 - Black screen upon win. Did not receive credit.

**Comment by eraffxi** [comment] 2016-07-30 09:14
adding player:bcnmleave(1) seems to have corrected this kind of issue for me, though not convinced that's the right way to do it

https://github.com/DarkstarProject/darkstar/issues/3300

**Comment by cowrevenge** [comment] 2016-08-12 23:47
I uploaded a fix for this today. If you still have an issue, the cs ID is probably incorrect in your lua.

**Comment by IBGrimie** [comment] 2017-08-02 19:29
Where does one enter the correct cs and player:bcnmleave(1)?  Trying to fix Moon Reading.  I tried to fix the sjob issue with the no mp and broke battleentities.ccp, 714 line error Mjob == 75.  Edited to 100.  Then the server broke...  So I replaced all the src with master copies and rebuilt the map server.  Up and running again but no mp for these mobs, no npc to save, and no exit or cs.  I find only the moon lit path in the BCNM folder.  I have no clue where BCNMID 225 is living. 

[12:13:40][Debug] BCNM 225 battlefield 1 : Battlefield has been locked. No more players can enter.
[12:13:41][Warning] CMagicState::ValidCast Mob (17473545) tried to cast magic with no mp!
[12:13:46][Info] parse: 01A | 00C7 00C6 0E from user: Rebel
[12:13:46][Debug] CLIENT Rebel PERFORMING ACTION 07
[12:13:49][Info] parse: 01A | 00CF 00CE 0E from user: Rebel
[12:13:49][Debug] CLIENT Rebel PERFORMING ACTION 07
[12:13:56][Info] parse: 01A | 00DE 00DD 0E from user: Rebel
[12:13:56][Debug] CLIENT Rebel PERFORMING ACTION 07
[12:14:01][Warning] CMagicState::ValidCast Mob (17473545) tried to cast magic with no mp!
[12:14:03][Info] parse: 01A | 00EF 00EE 0E from user: Rebel
[12:14:03][Debug] CLIENT Rebel PERFORMING ACTION 07
[12:14:06][Info] parse: 03A | 00F3 00F2 04 from user: Rebel
[12:14:10][Info] parse: 01A | 00FE 00FD 0E from user: Rebel
[12:14:11][Debug] CLIENT Rebel PERFORMING ACTION 02
[12:14:28][Warning] CMagicState::ValidCast Mob (17473545) tried to cast magic with no mp!
[12:14:46][Info] parse: 0B5 | 0151 0150 0C from user: Rebel
[12:14:51][Warning] CMagicState::ValidCast Mob (17473545) tried to cast magic with no mp!
[12:14:51][Info] parse: 01A | 015D 015B 0E from user: Rebel
[12:14:51][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:14:53][Info] parse: 01A | 0162 0160 0E from user: Rebel
[12:14:53][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:14:55][Info] parse: 01A | 0167 0165 0E from user: Rebel
[12:14:55][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:15:03][Info] parse: 01A | 0178 0176 0E from user: Rebel
[12:15:03][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:15:07][Info] parse: 01A | 0182 0180 0E from user: Rebel
[12:15:07][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:15:09][Info] parse: 01A | 0186 0184 0E from user: Rebel
[12:15:09][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:15:11][Info] parse: 03A | 018B 0189 04 from user: Rebel
[12:15:19][Info] parse: 01A | 01A0 019E 0E from user: Rebel
[12:15:19][Debug] CLIENT Rebel PERFORMING ACTION 03
[12:15:20][Debug] BCNM 225 battlefield 1 : Winning conditions met. Waiting 7 seconds before exiting battlefield.
[12:15:26][Debug] BCNM 225 battlefield 1 : Exiting battlefield.
still waiting...

**Comment by TeoTwawki** [comment] 2017-08-02 21:15
> So I replaced all the src with master copies and rebuilt the map server. Up and running again but no mp for these mobs, no npc to save, and no exit or cs. 


Sounds like you broke your database. See forums for help, it'll be to big/spammy to do in github messages.

**Comment by IBGrimie** [comment] 2017-08-03 02:09
Yep sure did...  Cleaned it twice.  Lost menu sounds too, before fixing
with VC.  The problem I am having with Moon Reading is that changing the
Mob Groups table says level 75 min/max for group 8862 and 8864.  Yet
checking in Mob pools for Yali and the Manticore, it says Mjob = 0 and Sjob
= 0.  I had no problem fixing this for 2 nm's that didn't have complete
data on the first build of this server.  Changing Yali's sub job to 37 and
main to 75 caused a break point.  VC blamed battleentity.ccp.  Mjob = 75
error.  This is where the server broke'd.  I cleaned and rebuilt, which I
lost sound, so I cleaned and hit build.  Got sound.  Moon Reading is not
fixed yet...  First, before breaking my server again.  How do I get these 2
nm's a sub jobs without breaking the server?  And then where does The BCNM
Moon Reading live?  Can't find a script or mention of it outside of the
data base, yet most of it is there.  The fail point in the BCNM is on the
cards death, no extra 2 nm's for round 2. Yali and the manticore don't load
unless I change it so all 6 load at the start.  After all 6 dead, and in
spite of not having the Taru NPC in the battle, the mission status
progressed, but no cs and no exit from the BCNM even after the timer
expired.  I simply added the lines to door in heaven's tower and that part
functions.

Yes I should get the chat thing...

**Comment by TeoTwawki** [comment] 2017-08-03 04:04
That discord thing maybe. I see you already found troubleshooting on forum. I'm trying to politely steer you off of here. Lets not go offtopic anymore, all that's got nothing to do with the original issue report. Btw, those fields aren't where levels go.

**Comment by IBGrimie** [comment] 2017-08-03 18:01
straight on topic... trying to fix Moon Reading broke my server.  Yep found
the closest match to my problem, via google search...  Yet I doubt warp is
the issue here.  My test server is running now, and I would like to break
it more trying to fix the things that are not complete.  I will share when
I can get the animation of rank 10, and  the trumpet to sound.  Considering
that changing the mob rules to 3 in the BCNMID for all six nm's (18 total,
3 Battlefields) makes the bcnm functional with bugs, bring warp, it would
be a step towards a fuller GitHub build.  I would guess, being that I can't
find moon reading, that without the cs functioning, the warp trigger won't
work.  it is 100% no exit, even for the other "party member".  I took 2
accounts to that one.  I used char_var.sql to see that I got mission
status 4 for killing all six.  I would love to know where this BCNM lives,
as it is not in scripts/global/zones/fullmoon.  All I have found is 225
BCNMid...  Surely there is more to this bcnm than just level restriction,
size of the party, and rules to spawn mobs. The mission status being
advanced tells me that this script lives somewhere...

Yes the tutorials are pretty good.  But I don't even want to write a script
until I find the home of Moon Reading.  See what is there, it lives
somewhere...  It half functions.

Here is my hax'd door.  No bells or whistles.
-----------------------------------
-- Area: Heaven's Tower
-- NPC:  Vestal Chamber (chamber of the Star Sibyl)
-- @pos 0.1 -49 37 242
-----------------------------------
package.loaded["scripts/zones/Heavens_Tower/TextIDs"] = nil;
-----------------------------------
require("scripts/globals/titles");
require("scripts/globals/keyitems");
require("scripts/globals/missions");
require("scripts/zones/Heavens_Tower/TextIDs");
-----------------------------------
-- onTrade Action
-----------------------------------
function onTrade(player,npc,trade)
end;
-----------------------------------
-- onTrigger Action
-----------------------------------
function onTrigger(player,npc)

    local CurrentMission = player:getCurrentMission(WINDURST);
    local MissionStatus = player:getVar("MissionStatus");

    if (CurrentMission == A_NEW_JOURNEY and MissionStatus == 0) then
        player:startEvent(0x0099);
    elseif (player:hasKeyItem(MESSAGE_TO_JEUNO_WINDURST)) then
        player:startEvent(0x00A6);
    elseif (player:getRank() == 5 and CurrentMission == 255 and
player:hasCompletedMission(WINDURST,THE_FINAL_SEAL) == false) then
        player:startEvent(0x00BE);
    elseif (player:hasKeyItem(BURNT_SEAL)) then
        player:startEvent(0x00C0);
    elseif (CurrentMission == THE_SHADOW_AWAITS and MissionStatus == 0) then
        player:startEvent(0x00D6);
    elseif (CurrentMission == THE_SHADOW_AWAITS and
player:hasKeyItem(SHADOW_FRAGMENT)) then
        player:startEvent(0x00D8);
    elseif (CurrentMission == SAINTLY_INVITATION and MissionStatus == 0)
then
        player:startEvent(0x0136);
    elseif (CurrentMission == SAINTLY_INVITATION and MissionStatus == 3)
then
        player:startEvent(0x0138);
    elseif (CurrentMission == DOLL_OF_THE_DEAD and MissionStatus == 2) then
        player:startEvent(0x016A);
    elseif (CurrentMission == MOON_READING and MissionStatus == 0) then
  player:startEvent (0x180);
 elseif (CurrentMission == MOON_READING and MissionStatus == 2) then
  player:startEvent (0x181);
 elseif (CurrentMission == MOON_READING and MissionStatus == 3) then
  player:startEvent (0x182);
 elseif (CurrentMission == MOON_READING and MissionStatus == 4) then
  player:startEvent (0x197);
 else
        player:startEvent(0x009A);
    end

    return 1;
end;
-----------------------------------
-- onEventUpdate
-----------------------------------
function onEventUpdate(player,csid,option)
    -- printf("CSID: %u",csid);
    -- printf("RESULT: %u",option);
end;
-----------------------------------
-- onEventFinish
-----------------------------------
function onEventFinish(player,csid,option)
    -- printf("CSID: %u",csid);
    -- printf("RESULT: %u",option);

    if (csid == 0x0099) then
        player:setVar("MissionStatus",1);
        player:delKeyItem(STAR_CRESTED_SUMMONS);
        player:addKeyItem(LETTER_TO_THE_AMBASSADOR);
        player:messageSpecial(KEYITEM_OBTAINED,LETTER_TO_THE_AMBASSADOR);
    elseif (csid == 0x00A6 or csid == 0x00BE) then
    elseif (csid == 0x00C0) then
            player:addMission(WINDURST,THE_FINAL_SEAL);
            player:addKeyItem(NEW_FEIYIN_SEAL);
            player:messageSpecial(KEYITEM_OBTAINED,NEW_FEIYIN_SEAL);
            player:setVar("MissionStatus",10);
            player:delKeyItem(MESSAGE_TO_JEUNO_WINDURST);
    elseif (csid == 0x00D6) then
        player:setVar("MissionStatus",2);
        player:delKeyItem(STAR_CRESTED_SUMMONS);
        player:addTitle(STARORDAINED_WARRIOR);
    elseif (csid == 0x0136) then
        player:setVar("MissionStatus",1);
        player:addTitle(HERO_ON_BEHALF_OF_WINDURST);
        player:addKeyItem(HOLY_ONES_INVITATION);
        player:messageSpecial(KEYITEM_OBTAINED,HOLY_ONES_INVITATION);
    elseif (csid == 0x0138) then
        finishMissionTimeline(player,3,csid,option);
    elseif (csid == 0x00C0 or csid == 0x00D8) then
        finishMissionTimeline(player,1,csid,option);
    elseif (csid == 0x016A) then
        player:setVar("MissionStatus",3);
 elseif (csid == 0x180) then
  player:setVar("MissionStatus",2);
 elseif (csid == 0x181) then
  player:setVar("WINDURST92",2);
 elseif (csid == 0x182) then
  player:setVar("MissionStatus",4);
 elseif (csid == 0x197) then
  player:completeMission(2,23);
  player:setRank(10);
  player:addGil(GIL_RATE,100000);
 end
end;

**Comment by TeoTwawki** [comment] 2017-08-03 23:47
>straight on topic... trying to fix Moon Reading broke my server. 

No no no. Thats not what this topic is. locked. No more text bombs.

**Comment by TeoTwawki** [comment] 2017-08-03 23:50
Dear other users: if you have anything important relating to BCNM win condition not executing ***on BCNM's we actually already have*** then please rely to me on discord, and I will add that info here.

Breaking your server attempting to implement ***new content*** by not knowing wtf you are doing is **not** on topic.

**Comment by TeoTwawki** [comment] 2017-08-03 23:54
p.s. I don't even know that this is still an issue. I've never seen it on win, only on running from bcnm.

@Hozu This still happen?

**Comment by TeoTwawki** [comment] 2019-07-10 21:31
open new issue if this is still happening

**Closed by TeoTwawki** 2019-07-10 21:31 UTC
