### ISSUE TITLE
ZM4 not triggering completion on end of BCNM

### ISSUE THREAD

**Issue by korietsu** [DarkstarProject/darkstar#1643] opened 2015-07-01 06:56 UTC
Players are not receiving KI or completion of ZM4/Start of ZM5 on successful finish/exit of BCNM.

**Comment by Zenny89** [comment] 2015-07-01 11:58
This is the same issue as #1425

**Comment by xdemolish** [comment] 2015-07-01 12:10
duplicate of #1425

**Closed by xdemolish** 2015-07-01 12:10 UTC
