### ISSUE TITLE
0 delay to fight

### ISSUE THREAD

**Issue by githubigssan** [DarkstarProject/darkstar#3298] opened 2016-07-27 14:25 UTC
**_I have:_**

0 delay to fight 
see video :  http://www.ffxisf.com/dagger_bug.mp4

- [ ] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [ ] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160427_0

**_Server Version_** (type `@revision` in game) **:**
30160427_0

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by takhlaq** [comment] 2016-07-27 17:28
duplicate of https://github.com/DarkstarProject/darkstar/issues/3296#issuecomment-235643504

**Closed by takhlaq** 2016-07-27 17:28 UTC

**Comment by TeoTwawki** [comment] 2016-07-28 02:56
@takhlaq looks more like he found a dagger that doesn't have a delay set in the item_weapon table. But since he didn't actually tell us which one, we can't check..The issue you linked as a duplicate looks to be about was about monk h2h having wrong delay calculation
