### ISSUE TITLE
Simurgh spawn

### ISSUE THREAD

**Issue by kurehaa** [DarkstarProject/darkstar#2269] opened 2015-10-15 17:03 UTC
hi there, i tried to do simurgh but he didnt spawned in 48h of camp, please check it, thx

**Comment by Deadwing888** [comment] 2015-10-17 04:25
Spawned initially on my test server, and re-spawned successfully once.

**Comment by Deadwing888** [comment] 2015-10-18 04:39
Kurehaa is right, there's something up with the Simurgh respawn. 

Did not show up after second death. Checked sql and all the spawn points are legit. This could be related to the problem that land kings have where they stop spawning after a few days.

**Comment by kurehaa** [comment] 2015-10-18 14:07
Deadwing, thanks for checking

**Comment by bendangelo** [comment] 2015-10-19 02:07
Marking this as high priority. This could unearth deeper problems with the code base. Someone's gotta take a look at this.

**Comment by Deadwing888** [comment] 2015-10-19 02:38
Simurgh did eventually show up. I'm wondering if the function isn't somehow adding the math.random time to the existing re-spawn? So initial pop and repop are fine, but second repop would take 2 days, third repop 3 days etc?

Just a hypothesis

**Comment by Deadwing888** [comment] 2015-10-20 05:25
He showed up normally on day 4. Odd, i'll continue testing.

**Comment by jwonesh** [comment] 2015-10-25 04:51
Hi all,

I am new to contributing; this is my first post. I have cloned the repo and set up a test environment to look at this issue (I thought it would be a good way for me to get familiar with the system and the implementation). I have found the following while tracing through the code:

At some point during death, CAIMobDummy::ActionDropItems() gets called. This is invoked via a switch that examines the CAIGeneral::m_ActionType member. If the state of this member (which belongs to the PMob object being passed around) is in ACTION_DROPITEMS, we enter the following worklow:

* Do dropitem logic.
* invoke: luautils::OnMobDeath(m_PMob, nullptr);

This invokes the corresponding onMobDeath() method defined in Simurgh.lua:

* mob:setRespawnTime(math.random((75600),(86400)));

This in turn invokes CLuaBaseEntity::setRespawnTime(lua_State* L), which basically does:

* set respawnTime in server memory
* record lastAction tick

And here is the important part:

<code>
if (PMob->PBattleAI->GetCurrentAction() == ACTION_NONE)
        {
            PMob->PBattleAI->SetCurrentAction(ACTION_SPAWN);
        }
</code>

Notice how I said earlier that the action state for the for the PMob object is ACTION_DROPITEMS. It appears to me that this conditional block will never get executed. I say this because I could not find any main loop which iterates over existing entities in ACTION_NONE and tries to spawn them; the ACTION_SPAWN is triggered by various lua script actions, none of which are done of Simurgh.

Thus, the only time Simurgh would respawn would be when the server is restarted.

Is my analysis correct? I know that my knowledge is quite limited when it comes to C++, Lua, and this project (I work with Enterprise Java, so I at least have a small frame of reference).

**Comment by teschnei** [comment] 2015-10-25 05:39
there must be something more than that, or else no mob at all would respawn
(or at least every mob that drops items)

were you just reading the code or stepping through with the debugger?

**Comment by jwonesh** [comment] 2015-10-25 05:55
I was simply reading code, but I have begun debugging. Still haven't found a main loop for updating state of all entites to ACTION_SPAWN (I still believe it is event driven), but I am also not convinced that my theory is correct.

**Comment by teschnei** [comment] 2015-10-25 06:39
there is none, ACTION_SPAWN is really the act of "spawning" (or waiting to
spawn), and none is for things that don't spawn on a timer (popped
NMs/npcs, etc)

which is why it goes into either NONE or SPAWN when they die

**Comment by jwonesh** [comment] 2015-10-25 06:49
yes, I see that this code sets it correctly:

m_ActionType  = m_PMob->m_AllowRespawn ? ACTION_SPAWN : ACTION_NONE;

After stepping through, I cannot see any reason why Smirugh is bugged. I have debugged through and see all of the variables being set and read correctly. I will continue to look at it in the morning.

**Comment by Deadwing888** [comment] 2015-10-25 09:20
Simurgh began spawning normally after day 2, I'll see if I can figure out what was going on with the time he didn't.

In the meantime if you want to look at the respawn for faf/nid behe/KB and ada/aspid I can tell you for a fact that respawn is bugged. I suspect it's problems in lua having to do with handling the force pop+free pop.

**Comment by jwonesh** [comment] 2015-10-27 03:24
While this does not elucidate much about the issue, I generated some debug output for the state changes for Simurgh, form spawning all the way to death and respawning (I set respawn time to 0 seconds for testing):

ACTION_NONE (0 '\0') -> ACTION_SPAWN (25 '\x19')
ACTION_SPAWN (25 '\x19') -> ACTION_ROAMING (16 '\x10')
ACTION_ROAMING (16 '\x10') -> ACTION_FALL (20 '\x14')
ACTION_FALL (20 '\x14') -> ACTION_DROPITEMS (21 '\x15')
ACTION_DROPITEMS (21 '\x15') -> ACTION_DEATH (22 '\x16')
ACTION_DEATH (22 '\x16') -> ACTION_FADE_OUT (23 '\x17')
ACTION_FADE_OUT (23 '\x17') -> ACTION_SPAWN (25 '\x19')
ACTION_SPAWN (25 '\x19') -> ACTION_ROAMING (16 '\x10')

Nothing out of the ordinary there. I will try to induce a cast to see if I can get him to get stuck in a state.

**Comment by GiggleCait** [comment] 2015-12-20 20:51
Any news?

**Comment by Deadwing888** [comment] 2016-01-03 08:17
I think this is a @nasomi only issue.

**Comment by Deadwing888** [comment] 2016-01-29 18:29
Confirmed, this is not an issue with standard DSP code, only an issue on nas server. Can be closed

**Closed** 2016-01-29 18:39 UTC
Labels: High Priority
