### ISSUE TITLE
Maat Fight Impossible to Win on PLD (Oldschool Server)

### ISSUE THREAD

**Issue by Arthurdales** [DarkstarProject/darkstar#3148] opened 2016-05-07 13:02 UTC
**_I have:_**
- [x] searched existing issues (http://github.com/darkstarproject/darkstar/issues/) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:**
30160329_1

**_Server Version_** (type `@revision` in game) **:**
494588d

**_Source Branch_** (master/stable) **:**
master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
Haufy on Oldschool is trying to beat Maat but cannot because Maat is overpowered by his ability to continously attack.  Maat has a natural innate hundred fist ability and continously attacks. Also, his defense is very high.  Barely able to scratch him.  Haufy is fighting him on PLD with capped skills, using red bun curry for food, sleep potions to gain 100 TP at start, and icarus wing for another 100 TP, and cannot get Maat below 70% HP.  Hes fought Maat at least 8 times. I know because i keep funding his attempts by purchasing his food/medicine.  Can someone take a look and see if something can be done?

**Comment by Scavenge** [comment] 2016-05-10 17:38
can confirm this issue exists on stable as well

**Comment by TeoTwawki** [comment] 2016-05-10 19:24
That whole "set Maat job to yours and redo his stats for that job" thing seems to have broken

**Comment by eraffxi** [comment] 2016-05-17 08:18
you should maybe rename this to cover the way mnk mobs seem to be hundred fisting. alky gigas does it consistently, but just as well as all other mnk mobs im told

**Comment by bendangelo** [comment] 2016-05-17 19:28
@TeoTwawki that's not implemented right? I don't think that has ever been confirmed.

**Comment by TeoTwawki** [comment] 2016-05-17 21:53
@bendangelo Maat was working before, I dunno how long ago he broke, prolly before airewrite.

**Comment by Hozu** [comment] 2016-05-19 16:02
re: MNK mobs, or rather mobs that attack with h2h - how is their weapon delay calculated? Maybe the weapon specifically needs extra delay added to it like player h2h weapons have? I say weapon specifically because there are MNK mobs that attack with a non-h2h weapon and they're fine.

**Comment by eraffxi** [comment] 2016-05-21 00:22
turns out alky is actually a warrior job, apparently.  not sure if that really matters since maat has always done full on monk-style auto attacks and weaponskills despite the job he's set to on retail

**Comment by TeoTwawki** [comment] 2016-05-21 01:01
yeah Maat's supposed to melee as a monk and his "tp mobskills" are all duplicated of mnk ws
The only real difference is things like pld maat having Maats bash, different spell lists for blm Maat or rdm Maat, etc.

DSP _[does](https://github.com/DarkstarProject/darkstar/search?l=cpp&q=maat&utf8=%E2%9C%93)_ have code that is trying to basically apply the job stats of whatever job you are, on the fly, for your Maat fight. And that this is A) probably not working as it author intended and B) probably shouldn't have been done like that in the first place. There are multiple copies of him in multiple battlefields indicating that on retail there is one version per job and 3 per version (so that all 3 battle rooms can be occupied by 3 different players doing their Maat fight at once).

Also there are a ton of mobs with wrong delay values (mostly that they were never implemented though) in the DB. So far any I have checked that ppl told me do perma hundred fists have 0 (thats actually faster than hundred fists, its like instant death its so fast. Possibly because the minimum delay floor isn't applied for mobs).

Here's the actual line screwing with Maats melee delay. 
`PMob->m_Weapons[SLOT_MAIN]->setDelay((240*1000)/60);`
Prior to that in the DB he's set to exactly 300.
`INSERT INTO `mob_pools` VALUES (2460,'Maat',335,0x0000FA0200000000000000000000000000000000,2,2,1,300,100,0,0,0,0,18,0,0,0,3,0,0,0,1,0,335);`
For comparison, the majority of monk mobs are set to 360. A few are different values No idea if they should all have the same delay or not. If there are mistakes now, we can bet on people copy and pasting those mistakes to new mobs later. 

If there are "tiers" for mob h2h delay there should probably be some guidance added to the wiki about it.  (perhaps it was because of MA traits on mnk mobs? Does that even apply with mobs? If so I'd wager that being the reason for any having wrong melee speed when its not the zero delay problem)

**Comment by Hozu** [comment] 2016-05-21 02:31
@eraffxi - different issue entirely: https://github.com/DarkstarProject/darkstar/issues/2803

**Comment by Hozu** [comment] 2016-05-21 02:34
Mobs that attack with h2h should have their base delay set to the same as what Fruit Punches have, which is 520 it seems. https://github.com/DarkstarProject/darkstar/blob/master/sql/item_weapon.sql#L102

**Comment by TeoTwawki** [comment] 2016-05-21 02:51
@Hozu if that's the case every monk mob in db has had wrong delay since the beginning. I'd like to think somebody would have noticed that well before now...I really would..  (.\_.)

**Comment by Hozu** [comment] 2016-05-21 07:12
They worked fine for a long time, but somewhere in the past 6 months or so they started swinging a hell of a lot faster.

**Comment by TeoTwawki** [comment] 2016-05-21 07:15
yeah. The reason I said that was none of them have ever been 520.

**Comment by abriasffxi** [comment] 2016-08-27 17:54
Has anyone tried further to fix this?  I've been looking for something different than the delay (300) that is applied to him-

I noticed he has Triple Attack, any chance that's working incorrectly?  Anywhere he's getting a martial arts trait?  I can't find that but it would explain high level monk mobs being an issue.

On the delay side, I think most monk mobs are incredibly strong on DSP vs retail.  I remember the delay being much higher.

**Comment by abriasffxi** [comment] 2016-08-29 21:39
Alright, I did some more experimentation this morning.

First, changing the delay in the sql database does nothing for maat.  This prompted me to go down a rabbit hole.

The problem initially lies with the lines in mobutils.cpp.  I'm no coder, but check out the following:

`void SetupMaat(CMobEntity* PMob)
{
    // Should swing normally when not a mnk
    PMob->m_Weapons[SLOT_MAIN]->setDelay((240*1000)/60);

    switch(PMob->GetMJob()){
        case JOB_NIN:
            PMob->setMobMod(MOBMOD_DUAL_WIELD, 1);
            PMob->m_Weapons[SLOT_MAIN]->resetDelay();
            PMob->setMobMod(MOBMOD_SPECIAL_SKILL, 0);
            break;
        case JOB_DRK:
        case JOB_PLD:
            // Give shield bash
            PMob->setMobMod(MOBMOD_SPECIAL_SKILL, 1036);
            PMob->setMobMod(MOBMOD_SPECIAL_COOL, 50);
            PMob->setMobMod(MOBMOD_SPECIAL_DELAY, 40);
            break;
        case JOB_BST:
            // Call beast skill
            PMob->setMobMod(MOBMOD_SPECIAL_SKILL, 1017);
            PMob->setMobMod(MOBMOD_SPECIAL_COOL, 50);
            break;
    }
}`

So, this morning I record Maat's delay, using rough timing, as approximately 1.5seconds (delay~150?) between swings.  I don't have an accurate way of measuring time but I did it for more than a minute, so packet timing should be minor.

Next, I removed the entire line, PMob->m_Weapons[SLOT_MAIN]->setDelay((240*1000)/60);

I thought that this would use the default CalculateStats and return a delay in the database.  Instead, Maat attacked at basically infinite speed.  So, I changed his sql speed to 800.  He still attacked infinite.

I put the line back in and changed the delay to 480*1000/60.  After another 5 minutes of timing, his delay was about 4.5 seconds (delay~280?).

So, I don't understand much more, but it seems like:
a) That line shouldn't be there at all.  I believe whoever programmed intended to have hundred fist speed by default (for monk?), and then raise it to 240 for other jobs.  No clue.  This is botched.  Maat always uses hand2hand on retail, and its about 4 seconds delay.  I watched about 30 different youtube videos.  Note, for ranger he pulls out a bow and doesn't do that right now.
b) Monk mobs probably have martial arts applied.  This makes sense why monk mobs in particular have such ridiculous speeds and dps.  However, martial arts did not work out exactly in my testing of delay here.  This needs to be further experimented.
c) He's not using hundred fists on monk which will probably make it even easier than it already is with half the abilities broke.

So, I've hacked in a 440 delay on my server to account for rough delay timing but it would be great if someone who understands code could do this the right way.

**Comment by wrenffxi** [comment] 2019-03-11 21:05
this can close. maat was rewritten and no longer hulk-monks out

**Comment by TeoTwawki** [comment] 2019-03-11 23:05
wow, 2016 feels so far ago but this issue feels so recent.

Maat still has some retail inaccuracies but the original issue this was opened for it taken care of. Closing this and I intend to take care of the other things later, the discord for captures got me a few Maat fight videos+packets to work with on it.

**Closed by TeoTwawki** 2019-03-11 23:05 UTC
